
-- ============================================================================
-- Merge STG_STELLAR_ACCESSORIES to DW_STELLAR_ACCESSORIES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_ACCESSORIES
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_ACCESSORIES tgt
    USING STG_STELLAR_ACCESSORIES src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.ACCESSORY_NAME = src.ACCESSORY_NAME,
            tgt.POSITION_ORDER = src.POSITION_ORDER,
            tgt.FRONTEND_POSITION = src.FRONTEND_POSITION,
            tgt.SHORT_NAME = src.SHORT_NAME,
            tgt.ABBREVIATION = src.ABBREVIATION,
            tgt.IMAGE_URL = src.IMAGE_URL,
            tgt.PRICE = src.PRICE,
            tgt.DEPOSIT_AMOUNT = src.DEPOSIT_AMOUNT,
            tgt.TAX_EXEMPT = src.TAX_EXEMPT,
            tgt.MAX_OVERLAPPING_RENTALS = src.MAX_OVERLAPPING_RENTALS,
            tgt.FRONTEND_QTY_LIMIT = src.FRONTEND_QTY_LIMIT,
            tgt.USE_STRIPED_BACKGROUND = src.USE_STRIPED_BACKGROUND,
            tgt.BACKEND_AVAILABLE_DAYS = src.BACKEND_AVAILABLE_DAYS,
            tgt.FRONTEND_AVAILABLE_DAYS = src.FRONTEND_AVAILABLE_DAYS,
            tgt.MAX_SAME_DEPARTURES = src.MAX_SAME_DEPARTURES,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, ACCESSORY_NAME, POSITION_ORDER, FRONTEND_POSITION, SHORT_NAME, ABBREVIATION, IMAGE_URL, PRICE, DEPOSIT_AMOUNT, TAX_EXEMPT, MAX_OVERLAPPING_RENTALS, FRONTEND_QTY_LIMIT, USE_STRIPED_BACKGROUND, BACKEND_AVAILABLE_DAYS, FRONTEND_AVAILABLE_DAYS, MAX_SAME_DEPARTURES, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.ACCESSORY_NAME, src.POSITION_ORDER, src.FRONTEND_POSITION, src.SHORT_NAME, src.ABBREVIATION, src.IMAGE_URL, src.PRICE, src.DEPOSIT_AMOUNT, src.TAX_EXEMPT, src.MAX_OVERLAPPING_RENTALS, src.FRONTEND_QTY_LIMIT, src.USE_STRIPED_BACKGROUND, src.BACKEND_AVAILABLE_DAYS, src.FRONTEND_AVAILABLE_DAYS, src.MAX_SAME_DEPARTURES, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_ACCESSORIES: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_ACCESSORIES: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_ACCESSORIES;
/
