
-- ============================================================================
-- Merge STG_MOLO_INVOICES to DW_MOLO_INVOICES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_INVOICES(
    p_inserted_count OUT NUMBER,
    p_updated_count OUT NUMBER
)
IS
BEGIN
    -- Insert new records that don't exist in DW
    INSERT INTO DW_MOLO_INVOICES (
        ID, DATE_FIELD, DOLLAR_DISCOUNT, PERCENT_DISCOUNT, ACTIVE, CLOSING_DATE, 
        DISCOUNT_TOTAL, OPENED, PAYED, SUBTOTAL, SUBTOTAL_WO_DISCOUNT, TAX_TOTAL, 
        TITLE, TOTAL, RESERVATION_ID, ACCOUNT_ID, SERVICE_PAID_AMOUNT, 
        MARINA_PAID_AMOUNT, GAS_PAID_AMOUNT, INVOICE_STATUS_ID, START_DATE, 
        INSTALLMENTS_PAYMENT_METHOD_ID, SCHEDULED_FOR_CRON, ORIGINAL_INVOICE, 
        PAYMENTS_SENT_TO_XERO, WORK_ORDER_ID, IS_INSTALLMENT_INVOICE, VOID_USER, 
        VOID_DATE_TIME, CREATION_USER, PAYMENT_ID, QB_INVOICE_ID, INVOICE_TYPE_ID, 
        INVOICE_DATE, DUE_DATE, CURRENCY_CODE, LAST_MODIFIED_DATE_TIME, 
        LAST_MODIFIED_ASPNET_USER, VOID_REASON, CREATE_PARTNER_ID, VOID_PARTNER_ID, 
        UPDATE_HASH, SCHEDULED_FOR_INVENTORY_CRON, SCHEDULED_FOR_SUBLET_CRON, 
        SCHEDULED_FOR_LABOR_CRON, CREATED_ON_MOBILE, STRIPE_INVOICE_ID, 
        SENT_TO_STRIPE, RESOURCE_BOOKING_ID, MODIFIED_ON_MOBILE, NOTE, 
        QUICKBOOKS_INVOICE_ID, TAX_CAP, IS_SURCHARGE, HASH_CHECK,
        DW_LAST_INSERTED,
        DW_LAST_UPDATED
    )
    SELECT 
        src.ID, src.DATE_FIELD, src.DOLLAR_DISCOUNT, src.PERCENT_DISCOUNT, src.ACTIVE, 
        src.CLOSING_DATE, src.DISCOUNT_TOTAL, src.OPENED, src.PAYED, src.SUBTOTAL, 
        src.SUBTOTAL_WO_DISCOUNT, src.TAX_TOTAL, src.TITLE, src.TOTAL, 
        src.RESERVATION_ID, src.ACCOUNT_ID, src.SERVICE_PAID_AMOUNT, 
        src.MARINA_PAID_AMOUNT, src.GAS_PAID_AMOUNT, src.INVOICE_STATUS_ID, 
        src.START_DATE, src.INSTALLMENTS_PAYMENT_METHOD_ID, src.SCHEDULED_FOR_CRON, 
        src.ORIGINAL_INVOICE, src.PAYMENTS_SENT_TO_XERO, src.WORK_ORDER_ID, 
        src.IS_INSTALLMENT_INVOICE, src.VOID_USER, src.VOID_DATE_TIME, 
        src.CREATION_USER, src.PAYMENT_ID, src.QB_INVOICE_ID, src.INVOICE_TYPE_ID, 
        src.INVOICE_DATE, src.DUE_DATE, src.CURRENCY_CODE, src.LAST_MODIFIED_DATE_TIME, 
        src.LAST_MODIFIED_ASPNET_USER, src.VOID_REASON, src.CREATE_PARTNER_ID, 
        src.VOID_PARTNER_ID, src.UPDATE_HASH, src.SCHEDULED_FOR_INVENTORY_CRON, 
        src.SCHEDULED_FOR_SUBLET_CRON, src.SCHEDULED_FOR_LABOR_CRON, 
        src.CREATED_ON_MOBILE, src.STRIPE_INVOICE_ID, src.SENT_TO_STRIPE, 
        src.RESOURCE_BOOKING_ID, src.MODIFIED_ON_MOBILE, src.NOTE, 
        src.QUICKBOOKS_INVOICE_ID, src.TAX_CAP, src.IS_SURCHARGE, src.HASH_CHECK,
        SYSTIMESTAMP,
        SYSTIMESTAMP
    FROM STG_MOLO_INVOICES src
    WHERE NOT EXISTS (
        SELECT 1 FROM DW_MOLO_INVOICES tgt WHERE tgt.ID = src.ID
    );
    
    p_inserted_count := SQL%ROWCOUNT;
    
    -- Update existing records where data has changed
    UPDATE DW_MOLO_INVOICES tgt
    SET (
        tgt.DATE_FIELD, tgt.DOLLAR_DISCOUNT, tgt.PERCENT_DISCOUNT, tgt.ACTIVE, 
        tgt.CLOSING_DATE, tgt.DISCOUNT_TOTAL, tgt.OPENED, tgt.PAYED, tgt.SUBTOTAL, 
        tgt.SUBTOTAL_WO_DISCOUNT, tgt.TAX_TOTAL, tgt.TITLE, tgt.TOTAL, 
        tgt.RESERVATION_ID, tgt.ACCOUNT_ID, tgt.SERVICE_PAID_AMOUNT, 
        tgt.MARINA_PAID_AMOUNT, tgt.GAS_PAID_AMOUNT, tgt.INVOICE_STATUS_ID, 
        tgt.START_DATE, tgt.INSTALLMENTS_PAYMENT_METHOD_ID, tgt.SCHEDULED_FOR_CRON, 
        tgt.ORIGINAL_INVOICE, tgt.PAYMENTS_SENT_TO_XERO, tgt.WORK_ORDER_ID, 
        tgt.IS_INSTALLMENT_INVOICE, tgt.VOID_USER, tgt.VOID_DATE_TIME, 
        tgt.CREATION_USER, tgt.PAYMENT_ID, tgt.QB_INVOICE_ID, tgt.INVOICE_TYPE_ID, 
        tgt.INVOICE_DATE, tgt.DUE_DATE, tgt.CURRENCY_CODE, tgt.LAST_MODIFIED_DATE_TIME, 
        tgt.LAST_MODIFIED_ASPNET_USER, tgt.VOID_REASON, tgt.CREATE_PARTNER_ID, 
        tgt.VOID_PARTNER_ID, tgt.UPDATE_HASH, tgt.SCHEDULED_FOR_INVENTORY_CRON, 
        tgt.SCHEDULED_FOR_SUBLET_CRON, tgt.SCHEDULED_FOR_LABOR_CRON, 
        tgt.CREATED_ON_MOBILE, tgt.STRIPE_INVOICE_ID, tgt.SENT_TO_STRIPE, 
        tgt.RESOURCE_BOOKING_ID, tgt.MODIFIED_ON_MOBILE, tgt.NOTE, 
        tgt.QUICKBOOKS_INVOICE_ID, tgt.TAX_CAP, tgt.IS_SURCHARGE, tgt.HASH_CHECK,
        tgt.DW_LAST_UPDATED
    ) = (
        SELECT 
            src.DATE_FIELD, src.DOLLAR_DISCOUNT, src.PERCENT_DISCOUNT, src.ACTIVE, 
            src.CLOSING_DATE, src.DISCOUNT_TOTAL, src.OPENED, src.PAYED, src.SUBTOTAL, 
            src.SUBTOTAL_WO_DISCOUNT, src.TAX_TOTAL, src.TITLE, src.TOTAL, 
            src.RESERVATION_ID, src.ACCOUNT_ID, src.SERVICE_PAID_AMOUNT, 
            src.MARINA_PAID_AMOUNT, src.GAS_PAID_AMOUNT, src.INVOICE_STATUS_ID, 
            src.START_DATE, src.INSTALLMENTS_PAYMENT_METHOD_ID, src.SCHEDULED_FOR_CRON, 
            src.ORIGINAL_INVOICE, src.PAYMENTS_SENT_TO_XERO, src.WORK_ORDER_ID, 
            src.IS_INSTALLMENT_INVOICE, src.VOID_USER, src.VOID_DATE_TIME, 
            src.CREATION_USER, src.PAYMENT_ID, src.QB_INVOICE_ID, src.INVOICE_TYPE_ID, 
            src.INVOICE_DATE, src.DUE_DATE, src.CURRENCY_CODE, src.LAST_MODIFIED_DATE_TIME, 
            src.LAST_MODIFIED_ASPNET_USER, src.VOID_REASON, src.CREATE_PARTNER_ID, 
            src.VOID_PARTNER_ID, src.UPDATE_HASH, src.SCHEDULED_FOR_INVENTORY_CRON, 
            src.SCHEDULED_FOR_SUBLET_CRON, src.SCHEDULED_FOR_LABOR_CRON, 
            src.CREATED_ON_MOBILE, src.STRIPE_INVOICE_ID, src.SENT_TO_STRIPE, 
            src.RESOURCE_BOOKING_ID, src.MODIFIED_ON_MOBILE, src.NOTE, 
            src.QUICKBOOKS_INVOICE_ID, src.TAX_CAP, src.IS_SURCHARGE, src.HASH_CHECK,
            SYSTIMESTAMP
        FROM STG_MOLO_INVOICES src
        WHERE src.ID = tgt.ID
    )
    WHERE EXISTS (
        SELECT 1 FROM STG_MOLO_INVOICES src 
        WHERE src.ID = tgt.ID
        AND (
            -- Only update if data has actually changed
            NVL(tgt.DATE_FIELD, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DATE_FIELD, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DOLLAR_DISCOUNT, -1) != NVL(src.DOLLAR_DISCOUNT, -1)
            OR NVL(tgt.PERCENT_DISCOUNT, -1) != NVL(src.PERCENT_DISCOUNT, -1)
            OR NVL(tgt.ACTIVE, -1) != NVL(src.ACTIVE, -1)
            OR NVL(tgt.CLOSING_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CLOSING_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DISCOUNT_TOTAL, -1) != NVL(src.DISCOUNT_TOTAL, -1)
            OR NVL(tgt.OPENED, -1) != NVL(src.OPENED, -1)
            OR NVL(tgt.PAYED, -9999999) != NVL(src.PAYED, -9999999)
            OR NVL(tgt.SUBTOTAL, -1) != NVL(src.SUBTOTAL, -1)
            OR NVL(tgt.SUBTOTAL_WO_DISCOUNT, -1) != NVL(src.SUBTOTAL_WO_DISCOUNT, -1)
            OR NVL(tgt.TAX_TOTAL, -1) != NVL(src.TAX_TOTAL, -1)
            OR NVL(tgt.TITLE, '~') != NVL(src.TITLE, '~')
            OR NVL(tgt.TOTAL, -1) != NVL(src.TOTAL, -1)
            OR NVL(tgt.RESERVATION_ID, -1) != NVL(src.RESERVATION_ID, -1)
            OR NVL(tgt.ACCOUNT_ID, -1) != NVL(src.ACCOUNT_ID, -1)
            OR NVL(tgt.SERVICE_PAID_AMOUNT, -1) != NVL(src.SERVICE_PAID_AMOUNT, -1)
            OR NVL(tgt.MARINA_PAID_AMOUNT, -1) != NVL(src.MARINA_PAID_AMOUNT, -1)
            OR NVL(tgt.GAS_PAID_AMOUNT, -1) != NVL(src.GAS_PAID_AMOUNT, -1)
            OR NVL(tgt.INVOICE_STATUS_ID, -1) != NVL(src.INVOICE_STATUS_ID, -1)
            OR NVL(tgt.START_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.START_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.INSTALLMENTS_PAYMENT_METHOD_ID, -1) != NVL(src.INSTALLMENTS_PAYMENT_METHOD_ID, -1)
            OR NVL(tgt.SCHEDULED_FOR_CRON, -1) != NVL(src.SCHEDULED_FOR_CRON, -1)
            OR NVL(tgt.ORIGINAL_INVOICE, -1) != NVL(src.ORIGINAL_INVOICE, -1)
            OR NVL(tgt.PAYMENTS_SENT_TO_XERO, -1) != NVL(src.PAYMENTS_SENT_TO_XERO, -1)
            OR NVL(tgt.WORK_ORDER_ID, -1) != NVL(src.WORK_ORDER_ID, -1)
            OR NVL(tgt.IS_INSTALLMENT_INVOICE, -1) != NVL(src.IS_INSTALLMENT_INVOICE, -1)
            OR NVL(tgt.VOID_USER, '~') != NVL(src.VOID_USER, '~')
            OR NVL(tgt.VOID_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.VOID_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CREATION_USER, '~') != NVL(src.CREATION_USER, '~')
            OR NVL(tgt.PAYMENT_ID, -1) != NVL(src.PAYMENT_ID, -1)
            OR NVL(tgt.QB_INVOICE_ID, -1) != NVL(src.QB_INVOICE_ID, -1)
            OR NVL(tgt.INVOICE_TYPE_ID, -1) != NVL(src.INVOICE_TYPE_ID, -1)
            OR NVL(tgt.INVOICE_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.INVOICE_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DUE_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.DUE_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.CURRENCY_CODE, '~') != NVL(src.CURRENCY_CODE, '~')
            OR NVL(tgt.LAST_MODIFIED_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.LAST_MODIFIED_DATE_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.LAST_MODIFIED_ASPNET_USER, '~') != NVL(src.LAST_MODIFIED_ASPNET_USER, '~')
            OR NVL(tgt.VOID_REASON, '~') != NVL(src.VOID_REASON, '~')
            OR NVL(tgt.CREATE_PARTNER_ID, -1) != NVL(src.CREATE_PARTNER_ID, -1)
            OR NVL(tgt.VOID_PARTNER_ID, -1) != NVL(src.VOID_PARTNER_ID, -1)
            OR NVL(tgt.UPDATE_HASH, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.UPDATE_HASH, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.SCHEDULED_FOR_INVENTORY_CRON, -1) != NVL(src.SCHEDULED_FOR_INVENTORY_CRON, -1)
            OR NVL(tgt.SCHEDULED_FOR_SUBLET_CRON, -1) != NVL(src.SCHEDULED_FOR_SUBLET_CRON, -1)
            OR NVL(tgt.SCHEDULED_FOR_LABOR_CRON, -1) != NVL(src.SCHEDULED_FOR_LABOR_CRON, -1)
            OR NVL(tgt.CREATED_ON_MOBILE, -1) != NVL(src.CREATED_ON_MOBILE, -1)
            OR NVL(tgt.STRIPE_INVOICE_ID, '~') != NVL(src.STRIPE_INVOICE_ID, '~')
            OR NVL(tgt.SENT_TO_STRIPE, -1) != NVL(src.SENT_TO_STRIPE, -1)
            OR NVL(tgt.RESOURCE_BOOKING_ID, -1) != NVL(src.RESOURCE_BOOKING_ID, -1)
            OR NVL(tgt.MODIFIED_ON_MOBILE, -1) != NVL(src.MODIFIED_ON_MOBILE, -1)
            OR NVL(tgt.NOTE, '~') != NVL(src.NOTE, '~')
            OR NVL(tgt.QUICKBOOKS_INVOICE_ID, '~') != NVL(src.QUICKBOOKS_INVOICE_ID, '~')
            OR NVL(tgt.TAX_CAP, -1) != NVL(src.TAX_CAP, -1)
            OR NVL(tgt.IS_SURCHARGE, -1) != NVL(src.IS_SURCHARGE, -1)
            OR NVL(tgt.HASH_CHECK, -1) != NVL(src.HASH_CHECK, -1)
        )
    );
    
    p_updated_count := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_INVOICES: Inserted ' || p_inserted_count || ', Updated ' || p_updated_count || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_INVOICES: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_INVOICES;
