
  CREATE OR REPLACE EDITIONABLE PROCEDURE "API_USER"."SP_MERGE_STELLAR_STYLE_GROUPS" 
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_STYLE_GROUPS tgt
    USING STG_STELLAR_STYLE_GROUPS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.GROUP_NAME = src.GROUP_NAME,
            tgt.FRONTEND_MAX_SAME_DEPARTURES = src.FRONTEND_MAX_SAME_DEPARTURES,
            tgt.SAFETY_TEST_ENABLED = src.SAFETY_TEST_ENABLED,
            tgt.SAFETY_TEST_INSTRUCTIONS = src.SAFETY_TEST_INSTRUCTIONS,
            tgt.SAFETY_TEST_MIN_PERCENT_PASS = src.SAFETY_TEST_MIN_PERCENT_PASS,
            tgt.SAFETY_TEST_EXPIRATION_DAYS = src.SAFETY_TEST_EXPIRATION_DAYS,
            tgt.SAFETY_VIDEO_LINK = src.SAFETY_VIDEO_LINK,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, GROUP_NAME, FRONTEND_MAX_SAME_DEPARTURES, SAFETY_TEST_ENABLED, SAFETY_TEST_INSTRUCTIONS, SAFETY_TEST_MIN_PERCENT_PASS, SAFETY_TEST_EXPIRATION_DAYS, SAFETY_VIDEO_LINK, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.GROUP_NAME, src.FRONTEND_MAX_SAME_DEPARTURES, src.SAFETY_TEST_ENABLED, src.SAFETY_TEST_INSTRUCTIONS, src.SAFETY_TEST_MIN_PERCENT_PASS, src.SAFETY_TEST_EXPIRATION_DAYS, src.SAFETY_VIDEO_LINK, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_STYLE_GROUPS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_STYLE_GROUPS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_STYLE_GROUPS;
/