
  CREATE OR REPLACE EDITIONABLE PROCEDURE "API_USER"."SP_MERGE_STELLAR_CLUB_TIERS" 
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_CLUB_TIERS tgt
    USING STG_STELLAR_CLUB_TIERS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.TIER_NAME = src.TIER_NAME,
            tgt.FRONTEND_DISPLAY = src.FRONTEND_DISPLAY,
            tgt.FRONTEND_NAME = src.FRONTEND_NAME,
            tgt.FRONTEND_POSITION = src.FRONTEND_POSITION,
            tgt.TERM_LENGTH = src.TERM_LENGTH,
            tgt.TERM_LENGTH_TYPE = src.TERM_LENGTH_TYPE,
            tgt.TERM_AUTO_RENEW = src.TERM_AUTO_RENEW,
            tgt.TERM_FEE = src.TERM_FEE,
            tgt.PERIOD_LENGTH = src.PERIOD_LENGTH,
            tgt.PERIOD_LENGTH_TYPE = src.PERIOD_LENGTH_TYPE,
            tgt.CREDITS_PER_PERIOD = src.CREDITS_PER_PERIOD,
            tgt.HOURS_PER_CREDIT = src.HOURS_PER_CREDIT,
            tgt.PERIOD_FEE = src.PERIOD_FEE,
            tgt.FRONTEND_DISPLAY_PRICING = src.FRONTEND_DISPLAY_PRICING,
            tgt.NO_SHOW_FEE = src.NO_SHOW_FEE,
            tgt.ALLOW_SELF_CANCELLATIONS = src.ALLOW_SELF_CANCELLATIONS,
            tgt.CANCELLATION_FEE = src.CANCELLATION_FEE,
            tgt.APPLICATION_FEE = src.APPLICATION_FEE,
            tgt.BOAT_DAMAGE_RESPONSIBILITY_DEDUCTION = src.BOAT_DAMAGE_RESPONSIBILITY_DEDUCTION,
            tgt.MAX_PENDING_WAIT_LIST_ENTRIES = src.MAX_PENDING_WAIT_LIST_ENTRIES,
            tgt.FREE_ACCESSORIES = src.FREE_ACCESSORIES,
            tgt.DESCRIPTION_TEXT = src.DESCRIPTION_TEXT,
            tgt.TERMS_TEXT = src.TERMS_TEXT,
            tgt.STATUS_TIER = src.STATUS_TIER,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, TIER_NAME, FRONTEND_DISPLAY, FRONTEND_NAME, FRONTEND_POSITION, TERM_LENGTH, TERM_LENGTH_TYPE, TERM_AUTO_RENEW, TERM_FEE, PERIOD_LENGTH, PERIOD_LENGTH_TYPE, CREDITS_PER_PERIOD, HOURS_PER_CREDIT, PERIOD_FEE, FRONTEND_DISPLAY_PRICING, NO_SHOW_FEE, ALLOW_SELF_CANCELLATIONS, CANCELLATION_FEE, APPLICATION_FEE, BOAT_DAMAGE_RESPONSIBILITY_DEDUCTION, MAX_PENDING_WAIT_LIST_ENTRIES, FREE_ACCESSORIES, DESCRIPTION_TEXT, TERMS_TEXT, STATUS_TIER, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.TIER_NAME, src.FRONTEND_DISPLAY, src.FRONTEND_NAME, src.FRONTEND_POSITION, src.TERM_LENGTH, src.TERM_LENGTH_TYPE, src.TERM_AUTO_RENEW, src.TERM_FEE, src.PERIOD_LENGTH, src.PERIOD_LENGTH_TYPE, src.CREDITS_PER_PERIOD, src.HOURS_PER_CREDIT, src.PERIOD_FEE, src.FRONTEND_DISPLAY_PRICING, src.NO_SHOW_FEE, src.ALLOW_SELF_CANCELLATIONS, src.CANCELLATION_FEE, src.APPLICATION_FEE, src.BOAT_DAMAGE_RESPONSIBILITY_DEDUCTION, src.MAX_PENDING_WAIT_LIST_ENTRIES, src.FREE_ACCESSORIES, src.DESCRIPTION_TEXT, src.TERMS_TEXT, src.STATUS_TIER, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_CLUB_TIERS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_CLUB_TIERS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_CLUB_TIERS;
/