
-- ============================================================================
-- Merge STG_STELLAR_COUPONS to DW_STELLAR_COUPONS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_COUPONS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_COUPONS tgt
    USING STG_STELLAR_COUPONS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.CODE = src.CODE,
            tgt.COUPON_NAME = src.COUPON_NAME,
            tgt.COUPON_TYPE = src.COUPON_TYPE,
            tgt.COUPON_AMOUNT = src.COUPON_AMOUNT,
            tgt.COUNT_ALLOWED = src.COUNT_ALLOWED,
            tgt.COUNT_ALLOWED_DAILY = src.COUNT_ALLOWED_DAILY,
            tgt.COUNT_USED = src.COUNT_USED,
            tgt.RENTAL_START = src.RENTAL_START,
            tgt.RENTAL_END = src.RENTAL_END,
            tgt.COUPON_START = src.COUPON_START,
            tgt.COUPON_END = src.COUPON_END,
            tgt.MIN_DEPARTURE_TIME = src.MIN_DEPARTURE_TIME,
            tgt.MAX_DEPARTURE_TIME = src.MAX_DEPARTURE_TIME,
            tgt.MIN_RETURN_TIME = src.MIN_RETURN_TIME,
            tgt.MAX_RETURN_TIME = src.MAX_RETURN_TIME,
            tgt.MIN_HOURS = src.MIN_HOURS,
            tgt.MAX_HOURS = src.MAX_HOURS,
            tgt.MIN_HOURS_BEFORE_DEPARTURE = src.MIN_HOURS_BEFORE_DEPARTURE,
            tgt.MAX_HOURS_BEFORE_DEPARTURE = src.MAX_HOURS_BEFORE_DEPARTURE,
            tgt.MAX_SAME_DAY_PER_CUSTOMER = src.MAX_SAME_DAY_PER_CUSTOMER,
            tgt.MAX_ACTIVE_PER_CUSTOMER = src.MAX_ACTIVE_PER_CUSTOMER,
            tgt.DISABLE_CONSECUTIVE_PER_CUSTOMER = src.DISABLE_CONSECUTIVE_PER_CUSTOMER,
            tgt.STATUS_COUPON = src.STATUS_COUPON,
            tgt.VALID_DAYS = src.VALID_DAYS,
            tgt.HOLIDAYS_ONLY_IF_VALID_DAY = src.HOLIDAYS_ONLY_IF_VALID_DAY,
            tgt.VALID_STYLES = src.VALID_STYLES,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, CODE, COUPON_NAME, COUPON_TYPE, COUPON_AMOUNT, COUNT_ALLOWED, COUNT_ALLOWED_DAILY, COUNT_USED, RENTAL_START, RENTAL_END, COUPON_START, COUPON_END, MIN_DEPARTURE_TIME, MAX_DEPARTURE_TIME, MIN_RETURN_TIME, MAX_RETURN_TIME, MIN_HOURS, MAX_HOURS, MIN_HOURS_BEFORE_DEPARTURE, MAX_HOURS_BEFORE_DEPARTURE, MAX_SAME_DAY_PER_CUSTOMER, MAX_ACTIVE_PER_CUSTOMER, DISABLE_CONSECUTIVE_PER_CUSTOMER, STATUS_COUPON, VALID_DAYS, HOLIDAYS_ONLY_IF_VALID_DAY, VALID_STYLES, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.CODE, src.COUPON_NAME, src.COUPON_TYPE, src.COUPON_AMOUNT, src.COUNT_ALLOWED, src.COUNT_ALLOWED_DAILY, src.COUNT_USED, src.RENTAL_START, src.RENTAL_END, src.COUPON_START, src.COUPON_END, src.MIN_DEPARTURE_TIME, src.MAX_DEPARTURE_TIME, src.MIN_RETURN_TIME, src.MAX_RETURN_TIME, src.MIN_HOURS, src.MAX_HOURS, src.MIN_HOURS_BEFORE_DEPARTURE, src.MAX_HOURS_BEFORE_DEPARTURE, src.MAX_SAME_DAY_PER_CUSTOMER, src.MAX_ACTIVE_PER_CUSTOMER, src.DISABLE_CONSECUTIVE_PER_CUSTOMER, src.STATUS_COUPON, src.VALID_DAYS, src.HOLIDAYS_ONLY_IF_VALID_DAY, src.VALID_STYLES, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_COUPONS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_COUPONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_COUPONS;
/
