
  CREATE OR REPLACE EDITIONABLE PROCEDURE "API_USER"."SP_MERGE_MOLO_MARINA_LOCATIONS" 
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_MARINA_LOCATIONS tgt
    USING STG_MOLO_MARINA_LOCATIONS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.NAME = src.NAME,
            tgt.PRIMARY_PHONE_NUMBER = src.PRIMARY_PHONE_NUMBER,
            tgt.PRIMARY_FAX_NUMBER = src.PRIMARY_FAX_NUMBER,
            tgt.RULES = src.RULES,
            tgt.ARRIVAL_GUIDE = src.ARRIVAL_GUIDE,
            tgt.DEPOSIT_PERCENTAGE = src.DEPOSIT_PERCENTAGE,
            tgt.CITY_ID = src.CITY_ID,
            tgt.ORGANIZATION_ID = src.ORGANIZATION_ID,
            tgt.MARINA_HASH = src.MARINA_HASH,
            tgt.UNIT_SYSTEM = src.UNIT_SYSTEM,
            tgt.SAFETY_DISTANCE_W = src.SAFETY_DISTANCE_W,
            tgt.SAFETY_DISTANCE_L = src.SAFETY_DISTANCE_L,
            tgt.DEFAULT_ARRIVAL_TIME = src.DEFAULT_ARRIVAL_TIME,
            tgt.DEFAULT_DEPARTURE_TIME = src.DEFAULT_DEPARTURE_TIME,
            tgt.POLICY = src.POLICY,
            tgt.MAP = src.MAP,
            tgt.RETURNS_REFUNDS_POLICY = src.RETURNS_REFUNDS_POLICY,
            tgt.DEFAULT_TAX_RATE = src.DEFAULT_TAX_RATE,
            tgt.EMAIL_ADDRESS = src.EMAIL_ADDRESS,
            tgt.INVOICE_WARNING_DAY_COUNT = src.INVOICE_WARNING_DAY_COUNT,
            tgt.MARINA_WEBSITE = src.MARINA_WEBSITE,
            tgt.VESSEL_DIMENSIONS_OPTIONS = src.VESSEL_DIMENSIONS_OPTIONS,
            tgt.ALLOW_MOLO_ONLINE_PAYMENT = src.ALLOW_MOLO_ONLINE_PAYMENT,
            tgt.TIME_ZONE = src.TIME_ZONE,
            tgt.CURRENCIES_ID = src.CURRENCIES_ID,
            tgt.HASH_ID = src.HASH_ID,
            tgt.COUNTRY_ID = src.COUNTRY_ID,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, NAME, PRIMARY_PHONE_NUMBER, PRIMARY_FAX_NUMBER, RULES, ARRIVAL_GUIDE, DEPOSIT_PERCENTAGE, CITY_ID, ORGANIZATION_ID, MARINA_HASH, UNIT_SYSTEM, SAFETY_DISTANCE_W, SAFETY_DISTANCE_L, DEFAULT_ARRIVAL_TIME, DEFAULT_DEPARTURE_TIME, POLICY, MAP, RETURNS_REFUNDS_POLICY, DEFAULT_TAX_RATE, EMAIL_ADDRESS, INVOICE_WARNING_DAY_COUNT, MARINA_WEBSITE, VESSEL_DIMENSIONS_OPTIONS, ALLOW_MOLO_ONLINE_PAYMENT, TIME_ZONE, CURRENCIES_ID, HASH_ID, COUNTRY_ID,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.NAME, src.PRIMARY_PHONE_NUMBER, src.PRIMARY_FAX_NUMBER, src.RULES, src.ARRIVAL_GUIDE, src.DEPOSIT_PERCENTAGE, src.CITY_ID, src.ORGANIZATION_ID, src.MARINA_HASH, src.UNIT_SYSTEM, src.SAFETY_DISTANCE_W, src.SAFETY_DISTANCE_L, src.DEFAULT_ARRIVAL_TIME, src.DEFAULT_DEPARTURE_TIME, src.POLICY, src.MAP, src.RETURNS_REFUNDS_POLICY, src.DEFAULT_TAX_RATE, src.EMAIL_ADDRESS, src.INVOICE_WARNING_DAY_COUNT, src.MARINA_WEBSITE, src.VESSEL_DIMENSIONS_OPTIONS, src.ALLOW_MOLO_ONLINE_PAYMENT, src.TIME_ZONE, src.CURRENCIES_ID, src.HASH_ID, src.COUNTRY_ID,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_MARINA_LOCATIONS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_MARINA_LOCATIONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_MARINA_LOCATIONS;
/