
-- ============================================================================
-- Merge STG_STELLAR_STYLES to DW_STELLAR_STYLES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_STYLES
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_STYLES tgt
    USING STG_STELLAR_STYLES src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.LOCATION_ID = src.LOCATION_ID,
            tgt.STYLE_GROUP_ID = src.STYLE_GROUP_ID,
            tgt.STYLE_NAME = src.STYLE_NAME,
            tgt.BACKEND_DISPLAY = src.BACKEND_DISPLAY,
            tgt.POSITION_ORDER = src.POSITION_ORDER,
            tgt.TURN_AROUND_TIME = src.TURN_AROUND_TIME,
            tgt.DEPOSIT_AMOUNT = src.DEPOSIT_AMOUNT,
            tgt.MULTI_DAY_DEPOSIT_AMOUNT = src.MULTI_DAY_DEPOSIT_AMOUNT,
            tgt.PRE_AUTH_AMOUNT = src.PRE_AUTH_AMOUNT,
            tgt.FUEL_BURN_RATIO = src.FUEL_BURN_RATIO,
            tgt.TAX_1_RATE = src.TAX_1_RATE,
            tgt.TAX_2_RATE = src.TAX_2_RATE,
            tgt.INSURANCE_ENABLED = src.INSURANCE_ENABLED,
            tgt.INSURANCE_PRICING_TYPE = src.INSURANCE_PRICING_TYPE,
            tgt.INSURANCE_PRICING_RATE = src.INSURANCE_PRICING_RATE,
            tgt.INSURANCE_FIRST_DAY_PRICE = src.INSURANCE_FIRST_DAY_PRICE,
            tgt.GRATUITY_ENABLED = src.GRATUITY_ENABLED,
            tgt.GRATUITY_PRICING_RATE = src.GRATUITY_PRICING_RATE,
            tgt.PARKING_QTY_MULTIPLIER = src.PARKING_QTY_MULTIPLIER,
            tgt.FRONTEND_DISPLAY = src.FRONTEND_DISPLAY,
            tgt.FRONTEND_NAME = src.FRONTEND_NAME,
            tgt.FRONTEND_POSITION = src.FRONTEND_POSITION,
            tgt.FRONTEND_TYPE = src.FRONTEND_TYPE,
            tgt.FRONTEND_QTY_LIMIT = src.FRONTEND_QTY_LIMIT,
            tgt.FRONTEND_UNIT_SELECTOR = src.FRONTEND_UNIT_SELECTOR,
            tgt.FRONTEND_PARTIAL_PAYMENT_TYPE = src.FRONTEND_PARTIAL_PAYMENT_TYPE,
            tgt.FRONTEND_PARTIAL_PAYMENT_AMOUNT = src.FRONTEND_PARTIAL_PAYMENT_AMOUNT,
            tgt.BACKEND_MULTI_DAY_DISABLED = src.BACKEND_MULTI_DAY_DISABLED,
            tgt.MAX_SAME_STYLE_PER_BOOKING = src.MAX_SAME_STYLE_PER_BOOKING,
            tgt.FRONTEND_MIN_HOURS_ADVANCE_DEPARTURE = src.FRONTEND_MIN_HOURS_ADVANCE_DEPARTURE,
            tgt.BACKEND_HOURLY_ENABLED = src.BACKEND_HOURLY_ENABLED,
            tgt.WEEK_DAY_BACKEND_HOURLY_MIN_HOURS = src.WEEK_DAY_BACKEND_HOURLY_MIN_HOURS,
            tgt.WEEK_DAY_BACKEND_HOURLY_MAX_HOURS = src.WEEK_DAY_BACKEND_HOURLY_MAX_HOURS,
            tgt.WEEK_END_BACKEND_HOURLY_MIN_HOURS = src.WEEK_END_BACKEND_HOURLY_MIN_HOURS,
            tgt.WEEK_END_BACKEND_HOURLY_MAX_HOURS = src.WEEK_END_BACKEND_HOURLY_MAX_HOURS,
            tgt.HOLIDAY_BACKEND_HOURLY_MIN_HOURS = src.HOLIDAY_BACKEND_HOURLY_MIN_HOURS,
            tgt.HOLIDAY_BACKEND_HOURLY_MAX_HOURS = src.HOLIDAY_BACKEND_HOURLY_MAX_HOURS,
            tgt.FRONTEND_HOURLY_ENABLED = src.FRONTEND_HOURLY_ENABLED,
            tgt.WEEK_DAY_FRONTEND_HOURLY_MIN_HOURS = src.WEEK_DAY_FRONTEND_HOURLY_MIN_HOURS,
            tgt.WEEK_DAY_FRONTEND_HOURLY_MAX_HOURS = src.WEEK_DAY_FRONTEND_HOURLY_MAX_HOURS,
            tgt.WEEK_DAY_FRONTEND_HOURLY_TIME_INCREMENT = src.WEEK_DAY_FRONTEND_HOURLY_TIME_INCREMENT,
            tgt.WEEK_DAY_FRONTEND_HOURLY_LENGTH_INCREMENT = src.WEEK_DAY_FRONTEND_HOURLY_LENGTH_INCREMENT,
            tgt.WEEK_END_FRONTEND_HOURLY_MIN_HOURS = src.WEEK_END_FRONTEND_HOURLY_MIN_HOURS,
            tgt.WEEK_END_FRONTEND_HOURLY_MAX_HOURS = src.WEEK_END_FRONTEND_HOURLY_MAX_HOURS,
            tgt.WEEK_END_FRONTEND_HOURLY_TIME_INCREMENT = src.WEEK_END_FRONTEND_HOURLY_TIME_INCREMENT,
            tgt.WEEK_END_FRONTEND_HOURLY_LENGTH_INCREMENT = src.WEEK_END_FRONTEND_HOURLY_LENGTH_INCREMENT,
            tgt.HOLIDAY_FRONTEND_HOURLY_MIN_HOURS = src.HOLIDAY_FRONTEND_HOURLY_MIN_HOURS,
            tgt.HOLIDAY_FRONTEND_HOURLY_MAX_HOURS = src.HOLIDAY_FRONTEND_HOURLY_MAX_HOURS,
            tgt.HOLIDAY_FRONTEND_HOURLY_TIME_INCREMENT = src.HOLIDAY_FRONTEND_HOURLY_TIME_INCREMENT,
            tgt.HOLIDAY_FRONTEND_HOURLY_LENGTH_INCREMENT = src.HOLIDAY_FRONTEND_HOURLY_LENGTH_INCREMENT,
            tgt.BACKEND_NIGHTLY_ENABLED = src.BACKEND_NIGHTLY_ENABLED,
            tgt.BACKEND_NIGHTLY_MIN_NIGHTS = src.BACKEND_NIGHTLY_MIN_NIGHTS,
            tgt.BACKEND_NIGHTLY_MAX_NIGHTS = src.BACKEND_NIGHTLY_MAX_NIGHTS,
            tgt.BACKEND_NIGHTLY_START = src.BACKEND_NIGHTLY_START,
            tgt.BACKEND_NIGHTLY_END = src.BACKEND_NIGHTLY_END,
            tgt.BACKEND_NIGHTLY_DISCOUNT_DAYS = src.BACKEND_NIGHTLY_DISCOUNT_DAYS,
            tgt.BACKEND_NIGHTLY_DISCOUNT_TYPE = src.BACKEND_NIGHTLY_DISCOUNT_TYPE,
            tgt.BACKEND_NIGHTLY_DISCOUNT_AMOUNT = src.BACKEND_NIGHTLY_DISCOUNT_AMOUNT,
            tgt.FRONTEND_NIGHTLY_ENABLED = src.FRONTEND_NIGHTLY_ENABLED,
            tgt.FRONTEND_NIGHTLY_MIN_NIGHTS = src.FRONTEND_NIGHTLY_MIN_NIGHTS,
            tgt.FRONTEND_NIGHTLY_MIN_NIGHTS_PEAK = src.FRONTEND_NIGHTLY_MIN_NIGHTS_PEAK,
            tgt.FRONTEND_NIGHTLY_MAX_NIGHTS = src.FRONTEND_NIGHTLY_MAX_NIGHTS,
            tgt.FRONTEND_NIGHTLY_START = src.FRONTEND_NIGHTLY_START,
            tgt.FRONTEND_NIGHTLY_END = src.FRONTEND_NIGHTLY_END,
            tgt.FRONTEND_NIGHTLY_ADDL_TIMES = src.FRONTEND_NIGHTLY_ADDL_TIMES,
            tgt.FRONTEND_NIGHTLY_DISCOUNT_DAYS = src.FRONTEND_NIGHTLY_DISCOUNT_DAYS,
            tgt.FRONTEND_NIGHTLY_DISCOUNT_TYPE = src.FRONTEND_NIGHTLY_DISCOUNT_TYPE,
            tgt.FRONTEND_NIGHTLY_DISCOUNT_AMOUNT = src.FRONTEND_NIGHTLY_DISCOUNT_AMOUNT,
            tgt.IMAGE_URL = src.IMAGE_URL,
            tgt.PASSENGERS = src.PASSENGERS,
            tgt.WEIGHT_CAPACITY = src.WEIGHT_CAPACITY,
            tgt.HORSEPOWER = src.HORSEPOWER,
            tgt.ENGINE_TYPE = src.ENGINE_TYPE,
            tgt.LENGTH_FEET = src.LENGTH_FEET,
            tgt.WIDTH_FEET = src.WIDTH_FEET,
            tgt.DRAFT_FEET = src.DRAFT_FEET,
            tgt.FUEL_CAPACITY = src.FUEL_CAPACITY,
            tgt.BRAND = src.BRAND,
            tgt.MODEL = src.MODEL,
            tgt.TITLE = src.TITLE,
            tgt.DESCRIPTION_TEXT = src.DESCRIPTION_TEXT,
            tgt.SUMMARY_TEXT = src.SUMMARY_TEXT,
            tgt.NOTES = src.NOTES,
            tgt.VIDEO_LINK = src.VIDEO_LINK,
            tgt.SMARTWAIVER_WAIVER_LINK = src.SMARTWAIVER_WAIVER_LINK,
            tgt.ACCOUNTING_ITEM_ID = src.ACCOUNTING_ITEM_ID,
            tgt.LOCAL_VIDEO_LINK = src.LOCAL_VIDEO_LINK,
            tgt.DOCKMASTER_PART_NUMBER = src.DOCKMASTER_PART_NUMBER,
            tgt.DOCKMASTER_TAX_CODE = src.DOCKMASTER_TAX_CODE,
            tgt.END_HOURS = src.END_HOURS,
            tgt.SEASONAL_BUFFER_DEFAULT_LOWER = src.SEASONAL_BUFFER_DEFAULT_LOWER,
            tgt.SEASONAL_BUFFER_DEFAULT_UPPER = src.SEASONAL_BUFFER_DEFAULT_UPPER,
            tgt.SEASONAL_BUFFER_PEAK_LOWER = src.SEASONAL_BUFFER_PEAK_LOWER,
            tgt.SEASONAL_BUFFER_PEAK_UPPER = src.SEASONAL_BUFFER_PEAK_UPPER,
            tgt.BILLABLE_UNIT_TYPE = src.BILLABLE_UNIT_TYPE,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, LOCATION_ID, STYLE_GROUP_ID, STYLE_NAME, BACKEND_DISPLAY, POSITION_ORDER, TURN_AROUND_TIME, DEPOSIT_AMOUNT, MULTI_DAY_DEPOSIT_AMOUNT, PRE_AUTH_AMOUNT, FUEL_BURN_RATIO, TAX_1_RATE, TAX_2_RATE, INSURANCE_ENABLED, INSURANCE_PRICING_TYPE, INSURANCE_PRICING_RATE, INSURANCE_FIRST_DAY_PRICE, GRATUITY_ENABLED, GRATUITY_PRICING_RATE, PARKING_QTY_MULTIPLIER, FRONTEND_DISPLAY, FRONTEND_NAME, FRONTEND_POSITION, FRONTEND_TYPE, FRONTEND_QTY_LIMIT, FRONTEND_UNIT_SELECTOR, FRONTEND_PARTIAL_PAYMENT_TYPE, FRONTEND_PARTIAL_PAYMENT_AMOUNT, BACKEND_MULTI_DAY_DISABLED, MAX_SAME_STYLE_PER_BOOKING, FRONTEND_MIN_HOURS_ADVANCE_DEPARTURE, BACKEND_HOURLY_ENABLED, WEEK_DAY_BACKEND_HOURLY_MIN_HOURS, WEEK_DAY_BACKEND_HOURLY_MAX_HOURS, WEEK_END_BACKEND_HOURLY_MIN_HOURS, WEEK_END_BACKEND_HOURLY_MAX_HOURS, HOLIDAY_BACKEND_HOURLY_MIN_HOURS, HOLIDAY_BACKEND_HOURLY_MAX_HOURS, FRONTEND_HOURLY_ENABLED, WEEK_DAY_FRONTEND_HOURLY_MIN_HOURS, WEEK_DAY_FRONTEND_HOURLY_MAX_HOURS, WEEK_DAY_FRONTEND_HOURLY_TIME_INCREMENT, WEEK_DAY_FRONTEND_HOURLY_LENGTH_INCREMENT, WEEK_END_FRONTEND_HOURLY_MIN_HOURS, WEEK_END_FRONTEND_HOURLY_MAX_HOURS, WEEK_END_FRONTEND_HOURLY_TIME_INCREMENT, WEEK_END_FRONTEND_HOURLY_LENGTH_INCREMENT, HOLIDAY_FRONTEND_HOURLY_MIN_HOURS, HOLIDAY_FRONTEND_HOURLY_MAX_HOURS, HOLIDAY_FRONTEND_HOURLY_TIME_INCREMENT, HOLIDAY_FRONTEND_HOURLY_LENGTH_INCREMENT, BACKEND_NIGHTLY_ENABLED, BACKEND_NIGHTLY_MIN_NIGHTS, BACKEND_NIGHTLY_MAX_NIGHTS, BACKEND_NIGHTLY_START, BACKEND_NIGHTLY_END, BACKEND_NIGHTLY_DISCOUNT_DAYS, BACKEND_NIGHTLY_DISCOUNT_TYPE, BACKEND_NIGHTLY_DISCOUNT_AMOUNT, FRONTEND_NIGHTLY_ENABLED, FRONTEND_NIGHTLY_MIN_NIGHTS, FRONTEND_NIGHTLY_MIN_NIGHTS_PEAK, FRONTEND_NIGHTLY_MAX_NIGHTS, FRONTEND_NIGHTLY_START, FRONTEND_NIGHTLY_END, FRONTEND_NIGHTLY_ADDL_TIMES, FRONTEND_NIGHTLY_DISCOUNT_DAYS, FRONTEND_NIGHTLY_DISCOUNT_TYPE, FRONTEND_NIGHTLY_DISCOUNT_AMOUNT, IMAGE_URL, PASSENGERS, WEIGHT_CAPACITY, HORSEPOWER, ENGINE_TYPE, LENGTH_FEET, WIDTH_FEET, DRAFT_FEET, FUEL_CAPACITY, BRAND, MODEL, TITLE, DESCRIPTION_TEXT, SUMMARY_TEXT, NOTES, VIDEO_LINK, SMARTWAIVER_WAIVER_LINK, ACCOUNTING_ITEM_ID, LOCAL_VIDEO_LINK, DOCKMASTER_PART_NUMBER, DOCKMASTER_TAX_CODE, END_HOURS, SEASONAL_BUFFER_DEFAULT_LOWER, SEASONAL_BUFFER_DEFAULT_UPPER, SEASONAL_BUFFER_PEAK_LOWER, SEASONAL_BUFFER_PEAK_UPPER, BILLABLE_UNIT_TYPE, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.LOCATION_ID, src.STYLE_GROUP_ID, src.STYLE_NAME, src.BACKEND_DISPLAY, src.POSITION_ORDER, src.TURN_AROUND_TIME, src.DEPOSIT_AMOUNT, src.MULTI_DAY_DEPOSIT_AMOUNT, src.PRE_AUTH_AMOUNT, src.FUEL_BURN_RATIO, src.TAX_1_RATE, src.TAX_2_RATE, src.INSURANCE_ENABLED, src.INSURANCE_PRICING_TYPE, src.INSURANCE_PRICING_RATE, src.INSURANCE_FIRST_DAY_PRICE, src.GRATUITY_ENABLED, src.GRATUITY_PRICING_RATE, src.PARKING_QTY_MULTIPLIER, src.FRONTEND_DISPLAY, src.FRONTEND_NAME, src.FRONTEND_POSITION, src.FRONTEND_TYPE, src.FRONTEND_QTY_LIMIT, src.FRONTEND_UNIT_SELECTOR, src.FRONTEND_PARTIAL_PAYMENT_TYPE, src.FRONTEND_PARTIAL_PAYMENT_AMOUNT, src.BACKEND_MULTI_DAY_DISABLED, src.MAX_SAME_STYLE_PER_BOOKING, src.FRONTEND_MIN_HOURS_ADVANCE_DEPARTURE, src.BACKEND_HOURLY_ENABLED, src.WEEK_DAY_BACKEND_HOURLY_MIN_HOURS, src.WEEK_DAY_BACKEND_HOURLY_MAX_HOURS, src.WEEK_END_BACKEND_HOURLY_MIN_HOURS, src.WEEK_END_BACKEND_HOURLY_MAX_HOURS, src.HOLIDAY_BACKEND_HOURLY_MIN_HOURS, src.HOLIDAY_BACKEND_HOURLY_MAX_HOURS, src.FRONTEND_HOURLY_ENABLED, src.WEEK_DAY_FRONTEND_HOURLY_MIN_HOURS, src.WEEK_DAY_FRONTEND_HOURLY_MAX_HOURS, src.WEEK_DAY_FRONTEND_HOURLY_TIME_INCREMENT, src.WEEK_DAY_FRONTEND_HOURLY_LENGTH_INCREMENT, src.WEEK_END_FRONTEND_HOURLY_MIN_HOURS, src.WEEK_END_FRONTEND_HOURLY_MAX_HOURS, src.WEEK_END_FRONTEND_HOURLY_TIME_INCREMENT, src.WEEK_END_FRONTEND_HOURLY_LENGTH_INCREMENT, src.HOLIDAY_FRONTEND_HOURLY_MIN_HOURS, src.HOLIDAY_FRONTEND_HOURLY_MAX_HOURS, src.HOLIDAY_FRONTEND_HOURLY_TIME_INCREMENT, src.HOLIDAY_FRONTEND_HOURLY_LENGTH_INCREMENT, src.BACKEND_NIGHTLY_ENABLED, src.BACKEND_NIGHTLY_MIN_NIGHTS, src.BACKEND_NIGHTLY_MAX_NIGHTS, src.BACKEND_NIGHTLY_START, src.BACKEND_NIGHTLY_END, src.BACKEND_NIGHTLY_DISCOUNT_DAYS, src.BACKEND_NIGHTLY_DISCOUNT_TYPE, src.BACKEND_NIGHTLY_DISCOUNT_AMOUNT, src.FRONTEND_NIGHTLY_ENABLED, src.FRONTEND_NIGHTLY_MIN_NIGHTS, src.FRONTEND_NIGHTLY_MIN_NIGHTS_PEAK, src.FRONTEND_NIGHTLY_MAX_NIGHTS, src.FRONTEND_NIGHTLY_START, src.FRONTEND_NIGHTLY_END, src.FRONTEND_NIGHTLY_ADDL_TIMES, src.FRONTEND_NIGHTLY_DISCOUNT_DAYS, src.FRONTEND_NIGHTLY_DISCOUNT_TYPE, src.FRONTEND_NIGHTLY_DISCOUNT_AMOUNT, src.IMAGE_URL, src.PASSENGERS, src.WEIGHT_CAPACITY, src.HORSEPOWER, src.ENGINE_TYPE, src.LENGTH_FEET, src.WIDTH_FEET, src.DRAFT_FEET, src.FUEL_CAPACITY, src.BRAND, src.MODEL, src.TITLE, src.DESCRIPTION_TEXT, src.SUMMARY_TEXT, src.NOTES, src.VIDEO_LINK, src.SMARTWAIVER_WAIVER_LINK, src.ACCOUNTING_ITEM_ID, src.LOCAL_VIDEO_LINK, src.DOCKMASTER_PART_NUMBER, src.DOCKMASTER_TAX_CODE, src.END_HOURS, src.SEASONAL_BUFFER_DEFAULT_LOWER, src.SEASONAL_BUFFER_DEFAULT_UPPER, src.SEASONAL_BUFFER_PEAK_LOWER, src.SEASONAL_BUFFER_PEAK_UPPER, src.BILLABLE_UNIT_TYPE, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_STYLES: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_STYLES: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_STYLES;
/
