
-- ============================================================================
-- Merge STG_MOLO_RESERVATIONS to DW_MOLO_RESERVATIONS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_RESERVATIONS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_RESERVATIONS tgt
    USING STG_MOLO_RESERVATIONS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.MARINA_LOCATION_ID = src.MARINA_LOCATION_ID,
            tgt.CREATION_TIME = src.CREATION_TIME,
            tgt.RESERVATION_STATUS_ID = src.RESERVATION_STATUS_ID,
            tgt.RESERVATION_TYPE_ID = src.RESERVATION_TYPE_ID,
            tgt.ASPNET_USER_ID = src.ASPNET_USER_ID,
            tgt.CONTACT_ID = src.CONTACT_ID,
            tgt.BOAT_ID = src.BOAT_ID,
            tgt.SCHEDULED_ARRIVAL_TIME = src.SCHEDULED_ARRIVAL_TIME,
            tgt.SCHEDULED_DEPARTURE_TIME = src.SCHEDULED_DEPARTURE_TIME,
            tgt.CANCELLATION_TIME = src.CANCELLATION_TIME,
            tgt.ACCOUNT_ID = src.ACCOUNT_ID,
            tgt.SLIP_ID = src.SLIP_ID,
            tgt.SLIP_SLOT_INDEX = src.SLIP_SLOT_INDEX,
            tgt.DISTANCE_FROM_THE_START = src.DISTANCE_FROM_THE_START,
            tgt.RATE = src.RATE,
            tgt.NAME = src.NAME,
            tgt.HAS_INSTALLMENTS = src.HAS_INSTALLMENTS,
            tgt.INSTALLMENT_FREQUENCY = src.INSTALLMENT_FREQUENCY,
            tgt.INSTALLMENT_NUMBER = src.INSTALLMENT_NUMBER,
            tgt.INSTALLMENT_PAYMENT_METHOD = src.INSTALLMENT_PAYMENT_METHOD,
            tgt.ONLY_RESERVATION_INSTALLMENTS = src.ONLY_RESERVATION_INSTALLMENTS,
            tgt.NOTES = src.NOTES,
            tgt.ACTUAL_ARRIVAL_DATE_TIME = src.ACTUAL_ARRIVAL_DATE_TIME,
            tgt.ACTUAL_DEPARTURE_DATE_TIME = src.ACTUAL_DEPARTURE_DATE_TIME,
            tgt.CONFIRMATION_EMAIL_DATE_TIME = src.CONFIRMATION_EMAIL_DATE_TIME,
            tgt.TERMS_ACCEPTED_DATE_TIME = src.TERMS_ACCEPTED_DATE_TIME,
            tgt.TERMS_ACCEPTED_LOCATION = src.TERMS_ACCEPTED_LOCATION,
            tgt.CUSTOMER_IP_ADDRESS = src.CUSTOMER_IP_ADDRESS,
            tgt.CUSTOMER_DEVICE = src.CUSTOMER_DEVICE,
            tgt.CONFIRMATION_EMAIL_ASP_USER_ID = src.CONFIRMATION_EMAIL_ASP_USER_ID,
            tgt.RATE_PRICE_OVERRIDE = src.RATE_PRICE_OVERRIDE,
            tgt.HASH_ID = src.HASH_ID,
            tgt.RESERVATION_SOURCE = src.RESERVATION_SOURCE,
            tgt.RESERVATION_MEDIUM_ID = src.RESERVATION_MEDIUM_ID,
            tgt.RESERVATION_CAMPAIGN_ID = src.RESERVATION_CAMPAIGN_ID,
            tgt.MOLO_API_PARTNER_ID = src.MOLO_API_PARTNER_ID,
            tgt.CANCELATION_USER_ID = src.CANCELATION_USER_ID,
            tgt.CONTACT_MERGED = src.CONTACT_MERGED,
            tgt.TRANSIENT_PRICE_ID = src.TRANSIENT_PRICE_ID,
            tgt.SEASONAL_PRICE_ID = src.SEASONAL_PRICE_ID,
            tgt.PRINTED_TERMS = src.PRINTED_TERMS,
            tgt.ONLINE_TERMS = src.ONLINE_TERMS,
            tgt.CHECK_IN_TERMS = src.CHECK_IN_TERMS,
            tgt.CHECK_OUT_TERMS = src.CHECK_OUT_TERMS,
            tgt.ONLINE_PAYMENT_COMPLETION = src.ONLINE_PAYMENT_COMPLETION,
            tgt.MOLO_ONLINE_BOOKING = src.MOLO_ONLINE_BOOKING,
            tgt.BOOKING_CONTACT_MERGED = src.BOOKING_CONTACT_MERGED,
            tgt.SLIP_BLOCK_SET_ID = src.SLIP_BLOCK_SET_ID,
            tgt.OFFERS_ID = src.OFFERS_ID,
            tgt.RECURRING_INVOICE_DAY = src.RECURRING_INVOICE_DAY,
            tgt.ALTERNATE_RESERVATION_NAME = src.ALTERNATE_RESERVATION_NAME,
            tgt.RECURRING_DISCOUNT_PERCENT = src.RECURRING_DISCOUNT_PERCENT,
            tgt.RECURRING_RATE_OVERRIDE = src.RECURRING_RATE_OVERRIDE,
            tgt.ONLINE_BOOKING_NOTES = src.ONLINE_BOOKING_NOTES,
            tgt.ORIGINAL_OFFER_HOLD_ID = src.ORIGINAL_OFFER_HOLD_ID,
            tgt.SCHEDULED_FOR_STATUS_CHANGE = src.SCHEDULED_FOR_STATUS_CHANGE,
            tgt.TERMS_OFFLINE = src.TERMS_OFFLINE,
            tgt.TERMS_USER = src.TERMS_USER,
            tgt.ORIGINAL_START_DATE = src.ORIGINAL_START_DATE,
            tgt.ORIGINAL_END_DATE = src.ORIGINAL_END_DATE,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, MARINA_LOCATION_ID, CREATION_TIME, RESERVATION_STATUS_ID, RESERVATION_TYPE_ID, ASPNET_USER_ID, CONTACT_ID, BOAT_ID, SCHEDULED_ARRIVAL_TIME, SCHEDULED_DEPARTURE_TIME, CANCELLATION_TIME, ACCOUNT_ID, SLIP_ID, SLIP_SLOT_INDEX, DISTANCE_FROM_THE_START, RATE, NAME, HAS_INSTALLMENTS, INSTALLMENT_FREQUENCY, INSTALLMENT_NUMBER, INSTALLMENT_PAYMENT_METHOD, ONLY_RESERVATION_INSTALLMENTS, NOTES, ACTUAL_ARRIVAL_DATE_TIME, ACTUAL_DEPARTURE_DATE_TIME, CONFIRMATION_EMAIL_DATE_TIME, TERMS_ACCEPTED_DATE_TIME, TERMS_ACCEPTED_LOCATION, CUSTOMER_IP_ADDRESS, CUSTOMER_DEVICE, CONFIRMATION_EMAIL_ASP_USER_ID, RATE_PRICE_OVERRIDE, HASH_ID, RESERVATION_SOURCE, RESERVATION_MEDIUM_ID, RESERVATION_CAMPAIGN_ID, MOLO_API_PARTNER_ID, CANCELATION_USER_ID, CONTACT_MERGED, TRANSIENT_PRICE_ID, SEASONAL_PRICE_ID, PRINTED_TERMS, ONLINE_TERMS, CHECK_IN_TERMS, CHECK_OUT_TERMS, ONLINE_PAYMENT_COMPLETION, MOLO_ONLINE_BOOKING, BOOKING_CONTACT_MERGED, SLIP_BLOCK_SET_ID, OFFERS_ID, RECURRING_INVOICE_DAY, ALTERNATE_RESERVATION_NAME, RECURRING_DISCOUNT_PERCENT, RECURRING_RATE_OVERRIDE, ONLINE_BOOKING_NOTES, ORIGINAL_OFFER_HOLD_ID, SCHEDULED_FOR_STATUS_CHANGE, TERMS_OFFLINE, TERMS_USER, ORIGINAL_START_DATE, ORIGINAL_END_DATE,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.MARINA_LOCATION_ID, src.CREATION_TIME, src.RESERVATION_STATUS_ID, src.RESERVATION_TYPE_ID, src.ASPNET_USER_ID, src.CONTACT_ID, src.BOAT_ID, src.SCHEDULED_ARRIVAL_TIME, src.SCHEDULED_DEPARTURE_TIME, src.CANCELLATION_TIME, src.ACCOUNT_ID, src.SLIP_ID, src.SLIP_SLOT_INDEX, src.DISTANCE_FROM_THE_START, src.RATE, src.NAME, src.HAS_INSTALLMENTS, src.INSTALLMENT_FREQUENCY, src.INSTALLMENT_NUMBER, src.INSTALLMENT_PAYMENT_METHOD, src.ONLY_RESERVATION_INSTALLMENTS, src.NOTES, src.ACTUAL_ARRIVAL_DATE_TIME, src.ACTUAL_DEPARTURE_DATE_TIME, src.CONFIRMATION_EMAIL_DATE_TIME, src.TERMS_ACCEPTED_DATE_TIME, src.TERMS_ACCEPTED_LOCATION, src.CUSTOMER_IP_ADDRESS, src.CUSTOMER_DEVICE, src.CONFIRMATION_EMAIL_ASP_USER_ID, src.RATE_PRICE_OVERRIDE, src.HASH_ID, src.RESERVATION_SOURCE, src.RESERVATION_MEDIUM_ID, src.RESERVATION_CAMPAIGN_ID, src.MOLO_API_PARTNER_ID, src.CANCELATION_USER_ID, src.CONTACT_MERGED, src.TRANSIENT_PRICE_ID, src.SEASONAL_PRICE_ID, src.PRINTED_TERMS, src.ONLINE_TERMS, src.CHECK_IN_TERMS, src.CHECK_OUT_TERMS, src.ONLINE_PAYMENT_COMPLETION, src.MOLO_ONLINE_BOOKING, src.BOOKING_CONTACT_MERGED, src.SLIP_BLOCK_SET_ID, src.OFFERS_ID, src.RECURRING_INVOICE_DAY, src.ALTERNATE_RESERVATION_NAME, src.RECURRING_DISCOUNT_PERCENT, src.RECURRING_RATE_OVERRIDE, src.ONLINE_BOOKING_NOTES, src.ORIGINAL_OFFER_HOLD_ID, src.SCHEDULED_FOR_STATUS_CHANGE, src.TERMS_OFFLINE, src.TERMS_USER, src.ORIGINAL_START_DATE, src.ORIGINAL_END_DATE,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_RESERVATIONS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_RESERVATIONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_RESERVATIONS;
/
