
-- ============================================================================
-- Merge STG_MOLO_SLIPS to DW_MOLO_SLIPS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_SLIPS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_SLIPS tgt
    USING STG_MOLO_SLIPS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.NAME = src.NAME,
            tgt.TYPE = src.TYPE,
            tgt.RECOMMENDED_LOA = src.RECOMMENDED_LOA,
            tgt.RECOMMENDED_BEAM = src.RECOMMENDED_BEAM,
            tgt.RECOMMENDED_DRAFT = src.RECOMMENDED_DRAFT,
            tgt.RECOMMENDED_AIR_DRAFT = src.RECOMMENDED_AIR_DRAFT,
            tgt.MAXIMUM_LOA = src.MAXIMUM_LOA,
            tgt.MAXIMUM_BEAM = src.MAXIMUM_BEAM,
            tgt.MAXIMUM_DRAFT = src.MAXIMUM_DRAFT,
            tgt.MAXIMUM_AIR_DRAFT = src.MAXIMUM_AIR_DRAFT,
            tgt.MARINA_LOCATION_ID = src.MARINA_LOCATION_ID,
            tgt.PIER_ID = src.PIER_ID,
            tgt.STATUS = src.STATUS,
            tgt.START_DATE = src.START_DATE,
            tgt.END_DATE = src.END_DATE,
            tgt.DO_NOT_COUNT_IN_OCCUPANCY = src.DO_NOT_COUNT_IN_OCCUPANCY,
            tgt.ACTIVE = src.ACTIVE,
            tgt.CREATION_DATE_TIME = src.CREATION_DATE_TIME,
            tgt.CREATION_USER = src.CREATION_USER,
            tgt.SLIP_TYPE_ID = src.SLIP_TYPE_ID,
            tgt.PAYMENT_PROCESSING_FEE = src.PAYMENT_PROCESSING_FEE,
            tgt.MANAGEMENT_FEE = src.MANAGEMENT_FEE,
            tgt.OWNER_ID = src.OWNER_ID,
            tgt.PAYMENT_PROCESSING_FEE_TYPE_ID = src.PAYMENT_PROCESSING_FEE_TYPE_ID,
            tgt.MANAGEMENT_FEE_TYPE_ID = src.MANAGEMENT_FEE_TYPE_ID,
            tgt.OVERRIDE_OCCUPANCY_LOA = src.OVERRIDE_OCCUPANCY_LOA,
            tgt.HASH_ID = src.HASH_ID,
            tgt.MAINTENANCE_FEE = src.MAINTENANCE_FEE,
            tgt.SVG_ID = src.SVG_ID,
            tgt.ASSESSMENT = src.ASSESSMENT,
            tgt.LOAN = src.LOAN,
            tgt.ORDER_COLUMN = src.ORDER_COLUMN,
            tgt.SIGN_NAME = src.SIGN_NAME,
            tgt.MAX_WEIGHT = src.MAX_WEIGHT,
            tgt.MAX_REVENUE = src.MAX_REVENUE,
            tgt.TRANSIENT_PRICE_ID = src.TRANSIENT_PRICE_ID,
            tgt.SEASONAL_PRICE_ID = src.SEASONAL_PRICE_ID,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, NAME, TYPE, RECOMMENDED_LOA, RECOMMENDED_BEAM, RECOMMENDED_DRAFT, RECOMMENDED_AIR_DRAFT, MAXIMUM_LOA, MAXIMUM_BEAM, MAXIMUM_DRAFT, MAXIMUM_AIR_DRAFT, MARINA_LOCATION_ID, PIER_ID, STATUS, START_DATE, END_DATE, DO_NOT_COUNT_IN_OCCUPANCY, ACTIVE, CREATION_DATE_TIME, CREATION_USER, SLIP_TYPE_ID, PAYMENT_PROCESSING_FEE, MANAGEMENT_FEE, OWNER_ID, PAYMENT_PROCESSING_FEE_TYPE_ID, MANAGEMENT_FEE_TYPE_ID, OVERRIDE_OCCUPANCY_LOA, HASH_ID, MAINTENANCE_FEE, SVG_ID, ASSESSMENT, LOAN, ORDER_COLUMN, SIGN_NAME, MAX_WEIGHT, MAX_REVENUE, TRANSIENT_PRICE_ID, SEASONAL_PRICE_ID,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.NAME, src.TYPE, src.RECOMMENDED_LOA, src.RECOMMENDED_BEAM, src.RECOMMENDED_DRAFT, src.RECOMMENDED_AIR_DRAFT, src.MAXIMUM_LOA, src.MAXIMUM_BEAM, src.MAXIMUM_DRAFT, src.MAXIMUM_AIR_DRAFT, src.MARINA_LOCATION_ID, src.PIER_ID, src.STATUS, src.START_DATE, src.END_DATE, src.DO_NOT_COUNT_IN_OCCUPANCY, src.ACTIVE, src.CREATION_DATE_TIME, src.CREATION_USER, src.SLIP_TYPE_ID, src.PAYMENT_PROCESSING_FEE, src.MANAGEMENT_FEE, src.OWNER_ID, src.PAYMENT_PROCESSING_FEE_TYPE_ID, src.MANAGEMENT_FEE_TYPE_ID, src.OVERRIDE_OCCUPANCY_LOA, src.HASH_ID, src.MAINTENANCE_FEE, src.SVG_ID, src.ASSESSMENT, src.LOAN, src.ORDER_COLUMN, src.SIGN_NAME, src.MAX_WEIGHT, src.MAX_REVENUE, src.TRANSIENT_PRICE_ID, src.SEASONAL_PRICE_ID,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_SLIPS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_SLIPS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_SLIPS;
/
