
-- ============================================================================
-- Merge STG_MOLO_INVOICES to DW_MOLO_INVOICES
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_INVOICES
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_MOLO_INVOICES tgt
    USING STG_MOLO_INVOICES src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.DATE_FIELD = src.DATE_FIELD,
            tgt.DOLLAR_DISCOUNT = src.DOLLAR_DISCOUNT,
            tgt.PERCENT_DISCOUNT = src.PERCENT_DISCOUNT,
            tgt.ACTIVE = src.ACTIVE,
            tgt.CLOSING_DATE = src.CLOSING_DATE,
            tgt.DISCOUNT_TOTAL = src.DISCOUNT_TOTAL,
            tgt.OPENED = src.OPENED,
            tgt.PAYED = src.PAYED,
            tgt.SUBTOTAL = src.SUBTOTAL,
            tgt.SUBTOTAL_WO_DISCOUNT = src.SUBTOTAL_WO_DISCOUNT,
            tgt.TAX_TOTAL = src.TAX_TOTAL,
            tgt.TITLE = src.TITLE,
            tgt.TOTAL = src.TOTAL,
            tgt.RESERVATION_ID = src.RESERVATION_ID,
            tgt.ACCOUNT_ID = src.ACCOUNT_ID,
            tgt.SERVICE_PAID_AMOUNT = src.SERVICE_PAID_AMOUNT,
            tgt.MARINA_PAID_AMOUNT = src.MARINA_PAID_AMOUNT,
            tgt.GAS_PAID_AMOUNT = src.GAS_PAID_AMOUNT,
            tgt.INVOICE_STATUS_ID = src.INVOICE_STATUS_ID,
            tgt.START_DATE = src.START_DATE,
            tgt.INSTALLMENTS_PAYMENT_METHOD_ID = src.INSTALLMENTS_PAYMENT_METHOD_ID,
            tgt.SCHEDULED_FOR_CRON = src.SCHEDULED_FOR_CRON,
            tgt.ORIGINAL_INVOICE = src.ORIGINAL_INVOICE,
            tgt.PAYMENTS_SENT_TO_XERO = src.PAYMENTS_SENT_TO_XERO,
            tgt.WORK_ORDER_ID = src.WORK_ORDER_ID,
            tgt.IS_INSTALLMENT_INVOICE = src.IS_INSTALLMENT_INVOICE,
            tgt.VOID_USER = src.VOID_USER,
            tgt.VOID_DATE_TIME = src.VOID_DATE_TIME,
            tgt.CREATION_USER = src.CREATION_USER,
            tgt.PAYMENT_ID = src.PAYMENT_ID,
            tgt.QB_INVOICE_ID = src.QB_INVOICE_ID,
            tgt.INVOICE_TYPE_ID = src.INVOICE_TYPE_ID,
            tgt.INVOICE_DATE = src.INVOICE_DATE,
            tgt.DUE_DATE = src.DUE_DATE,
            tgt.CURRENCY_CODE = src.CURRENCY_CODE,
            tgt.LAST_MODIFIED_DATE_TIME = src.LAST_MODIFIED_DATE_TIME,
            tgt.LAST_MODIFIED_ASPNET_USER = src.LAST_MODIFIED_ASPNET_USER,
            tgt.VOID_REASON = src.VOID_REASON,
            tgt.CREATE_PARTNER_ID = src.CREATE_PARTNER_ID,
            tgt.VOID_PARTNER_ID = src.VOID_PARTNER_ID,
            tgt.UPDATE_HASH = src.UPDATE_HASH,
            tgt.SCHEDULED_FOR_INVENTORY_CRON = src.SCHEDULED_FOR_INVENTORY_CRON,
            tgt.SCHEDULED_FOR_SUBLET_CRON = src.SCHEDULED_FOR_SUBLET_CRON,
            tgt.SCHEDULED_FOR_LABOR_CRON = src.SCHEDULED_FOR_LABOR_CRON,
            tgt.CREATED_ON_MOBILE = src.CREATED_ON_MOBILE,
            tgt.STRIPE_INVOICE_ID = src.STRIPE_INVOICE_ID,
            tgt.SENT_TO_STRIPE = src.SENT_TO_STRIPE,
            tgt.RESOURCE_BOOKING_ID = src.RESOURCE_BOOKING_ID,
            tgt.MODIFIED_ON_MOBILE = src.MODIFIED_ON_MOBILE,
            tgt.NOTE = src.NOTE,
            tgt.QUICKBOOKS_INVOICE_ID = src.QUICKBOOKS_INVOICE_ID,
            tgt.TAX_CAP = src.TAX_CAP,
            tgt.IS_SURCHARGE = src.IS_SURCHARGE,
            tgt.HASH_CHECK = src.HASH_CHECK,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, DATE_FIELD, DOLLAR_DISCOUNT, PERCENT_DISCOUNT, ACTIVE, CLOSING_DATE, DISCOUNT_TOTAL, OPENED, PAYED, SUBTOTAL, SUBTOTAL_WO_DISCOUNT, TAX_TOTAL, TITLE, TOTAL, RESERVATION_ID, ACCOUNT_ID, SERVICE_PAID_AMOUNT, MARINA_PAID_AMOUNT, GAS_PAID_AMOUNT, INVOICE_STATUS_ID, START_DATE, INSTALLMENTS_PAYMENT_METHOD_ID, SCHEDULED_FOR_CRON, ORIGINAL_INVOICE, PAYMENTS_SENT_TO_XERO, WORK_ORDER_ID, IS_INSTALLMENT_INVOICE, VOID_USER, VOID_DATE_TIME, CREATION_USER, PAYMENT_ID, QB_INVOICE_ID, INVOICE_TYPE_ID, INVOICE_DATE, DUE_DATE, CURRENCY_CODE, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_ASPNET_USER, VOID_REASON, CREATE_PARTNER_ID, VOID_PARTNER_ID, UPDATE_HASH, SCHEDULED_FOR_INVENTORY_CRON, SCHEDULED_FOR_SUBLET_CRON, SCHEDULED_FOR_LABOR_CRON, CREATED_ON_MOBILE, STRIPE_INVOICE_ID, SENT_TO_STRIPE, RESOURCE_BOOKING_ID, MODIFIED_ON_MOBILE, NOTE, QUICKBOOKS_INVOICE_ID, TAX_CAP, IS_SURCHARGE, HASH_CHECK,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.DATE_FIELD, src.DOLLAR_DISCOUNT, src.PERCENT_DISCOUNT, src.ACTIVE, src.CLOSING_DATE, src.DISCOUNT_TOTAL, src.OPENED, src.PAYED, src.SUBTOTAL, src.SUBTOTAL_WO_DISCOUNT, src.TAX_TOTAL, src.TITLE, src.TOTAL, src.RESERVATION_ID, src.ACCOUNT_ID, src.SERVICE_PAID_AMOUNT, src.MARINA_PAID_AMOUNT, src.GAS_PAID_AMOUNT, src.INVOICE_STATUS_ID, src.START_DATE, src.INSTALLMENTS_PAYMENT_METHOD_ID, src.SCHEDULED_FOR_CRON, src.ORIGINAL_INVOICE, src.PAYMENTS_SENT_TO_XERO, src.WORK_ORDER_ID, src.IS_INSTALLMENT_INVOICE, src.VOID_USER, src.VOID_DATE_TIME, src.CREATION_USER, src.PAYMENT_ID, src.QB_INVOICE_ID, src.INVOICE_TYPE_ID, src.INVOICE_DATE, src.DUE_DATE, src.CURRENCY_CODE, src.LAST_MODIFIED_DATE_TIME, src.LAST_MODIFIED_ASPNET_USER, src.VOID_REASON, src.CREATE_PARTNER_ID, src.VOID_PARTNER_ID, src.UPDATE_HASH, src.SCHEDULED_FOR_INVENTORY_CRON, src.SCHEDULED_FOR_SUBLET_CRON, src.SCHEDULED_FOR_LABOR_CRON, src.CREATED_ON_MOBILE, src.STRIPE_INVOICE_ID, src.SENT_TO_STRIPE, src.RESOURCE_BOOKING_ID, src.MODIFIED_ON_MOBILE, src.NOTE, src.QUICKBOOKS_INVOICE_ID, src.TAX_CAP, src.IS_SURCHARGE, src.HASH_CHECK,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_INVOICES: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_INVOICES: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_INVOICES;
/
