-- ============================================================================
-- Merge STG_MOLO_INVOICE_ITEMS to DW_MOLO_INVOICE_ITEMS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_INVOICE_ITEMS(
    p_inserted_count OUT NUMBER,
    p_updated_count OUT NUMBER
)
IS
BEGIN
    -- Insert new records that don't exist in DW
    INSERT INTO DW_MOLO_INVOICE_ITEMS (
        ID, PREFIX, QUANTITY, TITLE, TYPE_FIELD, VALUE_FIELD, DISCOUNT, DISCOUNT_TYPE, TAXABLE, TAX, MISC, DISCOUNT_TOTAL, PRICE_SUFFIX, SUB_TOTAL, SUBTOTAL_WO_DISCOUNT, TAX_TOTAL, TOTAL, INVOICE_ID, CHARGE_GROUP, PAYMENT_ACCOUNT, PRICE_STR, IS_VOID, DATE_FIELD, TEXT_AUX, TEXT_AUX2, DISCOUNT_DATE_TIME, DISCOUNT_USER_ID, NOTES, PR_TYPE, STATUS_FIELD, DELETION_USER_ID, DELETION_DATE_TIME, OVERPAYMENT_ID, VOID_USER, VOID_DATE_TIME, MISC2, PREPAYMENT_ID, CREDIT_INVOICE_ID, ALLOCATION_TYPE, RESERVATION_ID, ITEM_MASTER_ID, ASPNET_USER_ID, INVOICE_ITEM_TYPE_ID, SEASONAL_PRICE_ID, TRANSIENT_PRICE_ID, SV_JOB_ID, ORIGINAL_CREDIT_ITEM, TAX_EXEMPT, LAST_MODIFIED_DATE_TIME, LAST_MODIFIED_ASPNET_USER, DELETION_REASON, VOID_REASON, START_DATE_TIME, END_DATE_TIME, CREATION_PARTNER_ID, DELETE_PARTNER_ID, VOID_PARTNER_ID, ORIGINAL_PRICE, OVERRIDE_XERO_TAX_RATE, OVERRIDE_XERO_SALES_ACCOUNT, ORIGINAL_RESERVATION_PRICE, NUMBER_OF_DECIMALS, STRIPE_TRANSACTION_DATA_ID, VALUE_ALTERNATIVE, STRIPE_TERMINAL_ID, STRIPE_APPLICATION_NAME, STRIPE_AID, ENTERED_AMOUNT, EXCHANGE_RATE, CURRENCIES_ID, SV_CHARGE_INSTANCE_ID, SV_LABOR_INSTANCE_ID, SV_PART_INSTANCE_ID, REVENUE_GL_CODE, AR_GL_CODE, PAYMENT_GL_CODE, COGS_GL_CODE, INVENTORY_GL_CODE, SALES_TAX_GL_CODE, PREPAYMENT_GL_CODE, ACCOUNT_TYPE, APPLICATION_CRYPTOGRAM, AUTHORIZATION_CODE, AUTHORIZATION_RESPONSE_CODE, CARDHOLDER_VERIFICATION_METHOD, TERMINAL_VERIFICATION_RESULTS, TRANSACTION_STATUS_INFORMATION, TRACKING_CODE, DISCOUNT_GL_CODE, OVERRIDE_TRACKING_CATEGORY1, OVERRIDE_TRACKING_CATEGORY2, QUICKBOOKS_PAYMENT_ID, ALLOW_TOTAL_PRICE_ENTRY, ADDED_AUTOMATICALLY, ALLOCATION_PERFORMED_DATE, CREATED_DATE,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
    )
    SELECT 
        src.ID, src.PREFIX, src.QUANTITY, src.TITLE, src.TYPE_FIELD, src.VALUE_FIELD, src.DISCOUNT, src.DISCOUNT_TYPE, src.TAXABLE, src.TAX, src.MISC, src.DISCOUNT_TOTAL, src.PRICE_SUFFIX, src.SUB_TOTAL, src.SUBTOTAL_WO_DISCOUNT, src.TAX_TOTAL, src.TOTAL, src.INVOICE_ID, src.CHARGE_GROUP, src.PAYMENT_ACCOUNT, src.PRICE_STR, src.IS_VOID, src.DATE_FIELD, src.TEXT_AUX, src.TEXT_AUX2, src.DISCOUNT_DATE_TIME, src.DISCOUNT_USER_ID, src.NOTES, src.PR_TYPE, src.STATUS_FIELD, src.DELETION_USER_ID, src.DELETION_DATE_TIME, src.OVERPAYMENT_ID, src.VOID_USER, src.VOID_DATE_TIME, src.MISC2, src.PREPAYMENT_ID, src.CREDIT_INVOICE_ID, src.ALLOCATION_TYPE, src.RESERVATION_ID, src.ITEM_MASTER_ID, src.ASPNET_USER_ID, src.INVOICE_ITEM_TYPE_ID, src.SEASONAL_PRICE_ID, src.TRANSIENT_PRICE_ID, src.SV_JOB_ID, src.ORIGINAL_CREDIT_ITEM, src.TAX_EXEMPT, src.LAST_MODIFIED_DATE_TIME, src.LAST_MODIFIED_ASPNET_USER, src.DELETION_REASON, src.VOID_REASON, src.START_DATE_TIME, src.END_DATE_TIME, src.CREATION_PARTNER_ID, src.DELETE_PARTNER_ID, src.VOID_PARTNER_ID, src.ORIGINAL_PRICE, src.OVERRIDE_XERO_TAX_RATE, src.OVERRIDE_XERO_SALES_ACCOUNT, src.ORIGINAL_RESERVATION_PRICE, src.NUMBER_OF_DECIMALS, src.STRIPE_TRANSACTION_DATA_ID, src.VALUE_ALTERNATIVE, src.STRIPE_TERMINAL_ID, src.STRIPE_APPLICATION_NAME, src.STRIPE_AID, src.ENTERED_AMOUNT, src.EXCHANGE_RATE, src.CURRENCIES_ID, src.SV_CHARGE_INSTANCE_ID, src.SV_LABOR_INSTANCE_ID, src.SV_PART_INSTANCE_ID, src.REVENUE_GL_CODE, src.AR_GL_CODE, src.PAYMENT_GL_CODE, src.COGS_GL_CODE, src.INVENTORY_GL_CODE, src.SALES_TAX_GL_CODE, src.PREPAYMENT_GL_CODE, src.ACCOUNT_TYPE, src.APPLICATION_CRYPTOGRAM, src.AUTHORIZATION_CODE, src.AUTHORIZATION_RESPONSE_CODE, src.CARDHOLDER_VERIFICATION_METHOD, src.TERMINAL_VERIFICATION_RESULTS, src.TRANSACTION_STATUS_INFORMATION, src.TRACKING_CODE, src.DISCOUNT_GL_CODE, src.OVERRIDE_TRACKING_CATEGORY1, src.OVERRIDE_TRACKING_CATEGORY2, src.QUICKBOOKS_PAYMENT_ID, src.ALLOW_TOTAL_PRICE_ENTRY, src.ADDED_AUTOMATICALLY, src.ALLOCATION_PERFORMED_DATE, src.CREATED_DATE,
            SYSTIMESTAMP,
            SYSTIMESTAMP
    FROM STG_MOLO_INVOICE_ITEMS src
    WHERE NOT EXISTS (
        SELECT 1 FROM DW_MOLO_INVOICE_ITEMS tgt WHERE tgt.ID = src.ID
    );
    
    p_inserted_count := SQL%ROWCOUNT;
    
    -- Update existing records where data has changed
    UPDATE DW_MOLO_INVOICE_ITEMS tgt
    SET (
        tgt.PREFIX, tgt.QUANTITY, tgt.TITLE, tgt.TYPE_FIELD, tgt.VALUE_FIELD, tgt.DISCOUNT, tgt.DISCOUNT_TYPE, tgt.TAXABLE, tgt.TAX, tgt.MISC, tgt.DISCOUNT_TOTAL, tgt.PRICE_SUFFIX, tgt.SUB_TOTAL, tgt.SUBTOTAL_WO_DISCOUNT, tgt.TAX_TOTAL, tgt.TOTAL, tgt.INVOICE_ID, tgt.CHARGE_GROUP, tgt.PAYMENT_ACCOUNT, tgt.PRICE_STR, tgt.IS_VOID, tgt.DATE_FIELD, tgt.TEXT_AUX, tgt.TEXT_AUX2, tgt.DISCOUNT_DATE_TIME, tgt.DISCOUNT_USER_ID, tgt.NOTES, tgt.PR_TYPE, tgt.STATUS_FIELD, tgt.DELETION_USER_ID, tgt.DELETION_DATE_TIME, tgt.OVERPAYMENT_ID, tgt.VOID_USER, tgt.VOID_DATE_TIME, tgt.MISC2, tgt.PREPAYMENT_ID, tgt.CREDIT_INVOICE_ID, tgt.ALLOCATION_TYPE, tgt.RESERVATION_ID, tgt.ITEM_MASTER_ID, tgt.ASPNET_USER_ID, tgt.INVOICE_ITEM_TYPE_ID, tgt.SEASONAL_PRICE_ID, tgt.TRANSIENT_PRICE_ID, tgt.SV_JOB_ID, tgt.ORIGINAL_CREDIT_ITEM, tgt.TAX_EXEMPT, tgt.LAST_MODIFIED_DATE_TIME, tgt.LAST_MODIFIED_ASPNET_USER, tgt.DELETION_REASON, tgt.VOID_REASON, tgt.START_DATE_TIME, tgt.END_DATE_TIME, tgt.CREATION_PARTNER_ID, tgt.DELETE_PARTNER_ID, tgt.VOID_PARTNER_ID, tgt.ORIGINAL_PRICE, tgt.OVERRIDE_XERO_TAX_RATE, tgt.OVERRIDE_XERO_SALES_ACCOUNT, tgt.ORIGINAL_RESERVATION_PRICE, tgt.NUMBER_OF_DECIMALS, tgt.STRIPE_TRANSACTION_DATA_ID, tgt.VALUE_ALTERNATIVE, tgt.STRIPE_TERMINAL_ID, tgt.STRIPE_APPLICATION_NAME, tgt.STRIPE_AID, tgt.ENTERED_AMOUNT, tgt.EXCHANGE_RATE, tgt.CURRENCIES_ID, tgt.SV_CHARGE_INSTANCE_ID, tgt.SV_LABOR_INSTANCE_ID, tgt.SV_PART_INSTANCE_ID, tgt.REVENUE_GL_CODE, tgt.AR_GL_CODE, tgt.PAYMENT_GL_CODE, tgt.COGS_GL_CODE, tgt.INVENTORY_GL_CODE, tgt.SALES_TAX_GL_CODE, tgt.PREPAYMENT_GL_CODE, tgt.ACCOUNT_TYPE, tgt.APPLICATION_CRYPTOGRAM, tgt.AUTHORIZATION_CODE, tgt.AUTHORIZATION_RESPONSE_CODE, tgt.CARDHOLDER_VERIFICATION_METHOD, tgt.TERMINAL_VERIFICATION_RESULTS, tgt.TRANSACTION_STATUS_INFORMATION, tgt.TRACKING_CODE, tgt.DISCOUNT_GL_CODE, tgt.OVERRIDE_TRACKING_CATEGORY1, tgt.OVERRIDE_TRACKING_CATEGORY2, tgt.QUICKBOOKS_PAYMENT_ID, tgt.ALLOW_TOTAL_PRICE_ENTRY, tgt.ADDED_AUTOMATICALLY, tgt.ALLOCATION_PERFORMED_DATE, tgt.CREATED_DATE,
        tgt.DW_LAST_UPDATED
    ) = (
        SELECT 
            src.PREFIX, src.QUANTITY, src.TITLE, src.TYPE_FIELD, src.VALUE_FIELD, src.DISCOUNT, src.DISCOUNT_TYPE, src.TAXABLE, src.TAX, src.MISC, src.DISCOUNT_TOTAL, src.PRICE_SUFFIX, src.SUB_TOTAL, src.SUBTOTAL_WO_DISCOUNT, src.TAX_TOTAL, src.TOTAL, src.INVOICE_ID, src.CHARGE_GROUP, src.PAYMENT_ACCOUNT, src.PRICE_STR, src.IS_VOID, src.DATE_FIELD, src.TEXT_AUX, src.TEXT_AUX2, src.DISCOUNT_DATE_TIME, src.DISCOUNT_USER_ID, src.NOTES, src.PR_TYPE, src.STATUS_FIELD, src.DELETION_USER_ID, src.DELETION_DATE_TIME, src.OVERPAYMENT_ID, src.VOID_USER, src.VOID_DATE_TIME, src.MISC2, src.PREPAYMENT_ID, src.CREDIT_INVOICE_ID, src.ALLOCATION_TYPE, src.RESERVATION_ID, src.ITEM_MASTER_ID, src.ASPNET_USER_ID, src.INVOICE_ITEM_TYPE_ID, src.SEASONAL_PRICE_ID, src.TRANSIENT_PRICE_ID, src.SV_JOB_ID, src.ORIGINAL_CREDIT_ITEM, src.TAX_EXEMPT, src.LAST_MODIFIED_DATE_TIME, src.LAST_MODIFIED_ASPNET_USER, src.DELETION_REASON, src.VOID_REASON, src.START_DATE_TIME, src.END_DATE_TIME, src.CREATION_PARTNER_ID, src.DELETE_PARTNER_ID, src.VOID_PARTNER_ID, src.ORIGINAL_PRICE, src.OVERRIDE_XERO_TAX_RATE, src.OVERRIDE_XERO_SALES_ACCOUNT, src.ORIGINAL_RESERVATION_PRICE, src.NUMBER_OF_DECIMALS, src.STRIPE_TRANSACTION_DATA_ID, src.VALUE_ALTERNATIVE, src.STRIPE_TERMINAL_ID, src.STRIPE_APPLICATION_NAME, src.STRIPE_AID, src.ENTERED_AMOUNT, src.EXCHANGE_RATE, src.CURRENCIES_ID, src.SV_CHARGE_INSTANCE_ID, src.SV_LABOR_INSTANCE_ID, src.SV_PART_INSTANCE_ID, src.REVENUE_GL_CODE, src.AR_GL_CODE, src.PAYMENT_GL_CODE, src.COGS_GL_CODE, src.INVENTORY_GL_CODE, src.SALES_TAX_GL_CODE, src.PREPAYMENT_GL_CODE, src.ACCOUNT_TYPE, src.APPLICATION_CRYPTOGRAM, src.AUTHORIZATION_CODE, src.AUTHORIZATION_RESPONSE_CODE, src.CARDHOLDER_VERIFICATION_METHOD, src.TERMINAL_VERIFICATION_RESULTS, src.TRANSACTION_STATUS_INFORMATION, src.TRACKING_CODE, src.DISCOUNT_GL_CODE, src.OVERRIDE_TRACKING_CATEGORY1, src.OVERRIDE_TRACKING_CATEGORY2, src.QUICKBOOKS_PAYMENT_ID, src.ALLOW_TOTAL_PRICE_ENTRY, src.ADDED_AUTOMATICALLY, src.ALLOCATION_PERFORMED_DATE, src.CREATED_DATE,
            SYSTIMESTAMP
        FROM STG_MOLO_INVOICE_ITEMS src
        WHERE tgt.ID = src.ID
    )
    WHERE EXISTS (
        SELECT 1 FROM STG_MOLO_INVOICE_ITEMS src
        WHERE tgt.ID = src.ID
    );
    
    p_updated_count := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_INVOICE_ITEMS: Inserted ' || p_inserted_count || ', Updated ' || p_updated_count || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_INVOICE_ITEMS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_INVOICE_ITEMS;
