
-- ============================================================================
-- Merge STG_STELLAR_STYLE_BOATS to DW_STELLAR_STYLE_BOATS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_STYLE_BOATS
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_STYLE_BOATS tgt
    USING STG_STELLAR_STYLE_BOATS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.STYLE_ID = src.STYLE_ID,
            tgt.BOAT_NUMBER = src.BOAT_NUMBER,
            tgt.PAPER_LESS_NUMBER = src.PAPER_LESS_NUMBER,
            tgt.MOTOR = src.MOTOR,
            tgt.MANUFACTURER = src.MANUFACTURER,
            tgt.SERIAL_NUMBER = src.SERIAL_NUMBER,
            tgt.IN_FLEET = src.IN_FLEET,
            tgt.HULL_NUMBER = src.HULL_NUMBER,
            tgt.STATE_NUMBER = src.STATE_NUMBER,
            tgt.CYLINDERS = src.CYLINDERS,
            tgt.HP = src.HP,
            tgt.MODEL = src.MODEL,
            tgt.BOAT_TYPE = src.BOAT_TYPE,
            tgt.PURCHASED_DATE = src.PURCHASED_DATE,
            tgt.PURCHASED_COST = src.PURCHASED_COST,
            tgt.SALE_DATE = src.SALE_DATE,
            tgt.SALE_PRICE = src.SALE_PRICE,
            tgt.CLUB_LOCATION = src.CLUB_LOCATION,
            tgt.DEALER_NAME = src.DEALER_NAME,
            tgt.DEALER_CITY = src.DEALER_CITY,
            tgt.DEALER_STATE = src.DEALER_STATE,
            tgt.PO_NUMBER = src.PO_NUMBER,
            tgt.BOAT_YEAR_MODEL = src.BOAT_YEAR_MODEL,
            tgt.MOTOR_YEAR_MODEL = src.MOTOR_YEAR_MODEL,
            tgt.MOTOR_MANUFACTURER_MODEL = src.MOTOR_MANUFACTURER_MODEL,
            tgt.STATE_REG_DATE = src.STATE_REG_DATE,
            tgt.STATE_REG_EXP_DATE = src.STATE_REG_EXP_DATE,
            tgt.ENGINE_PURCHASED_COST = src.ENGINE_PURCHASED_COST,
            tgt.BACKEND_DISPLAY = src.BACKEND_DISPLAY,
            tgt.POSITION_ORDER = src.POSITION_ORDER,
            tgt.STATUS_BOAT = src.STATUS_BOAT,
            tgt.SERVICE_START = src.SERVICE_START,
            tgt.SERVICE_END = src.SERVICE_END,
            tgt.CLEAN_STATUS = src.CLEAN_STATUS,
            tgt.INSURANCE_REG_NO = src.INSURANCE_REG_NO,
            tgt.BUOY_INSURANCE_STATUS = src.BUOY_INSURANCE_STATUS,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, STYLE_ID, BOAT_NUMBER, PAPER_LESS_NUMBER, MOTOR, MANUFACTURER, SERIAL_NUMBER, IN_FLEET, HULL_NUMBER, STATE_NUMBER, CYLINDERS, HP, MODEL, BOAT_TYPE, PURCHASED_DATE, PURCHASED_COST, SALE_DATE, SALE_PRICE, CLUB_LOCATION, DEALER_NAME, DEALER_CITY, DEALER_STATE, PO_NUMBER, BOAT_YEAR_MODEL, MOTOR_YEAR_MODEL, MOTOR_MANUFACTURER_MODEL, STATE_REG_DATE, STATE_REG_EXP_DATE, ENGINE_PURCHASED_COST, BACKEND_DISPLAY, POSITION_ORDER, STATUS_BOAT, SERVICE_START, SERVICE_END, CLEAN_STATUS, INSURANCE_REG_NO, BUOY_INSURANCE_STATUS, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.STYLE_ID, src.BOAT_NUMBER, src.PAPER_LESS_NUMBER, src.MOTOR, src.MANUFACTURER, src.SERIAL_NUMBER, src.IN_FLEET, src.HULL_NUMBER, src.STATE_NUMBER, src.CYLINDERS, src.HP, src.MODEL, src.BOAT_TYPE, src.PURCHASED_DATE, src.PURCHASED_COST, src.SALE_DATE, src.SALE_PRICE, src.CLUB_LOCATION, src.DEALER_NAME, src.DEALER_CITY, src.DEALER_STATE, src.PO_NUMBER, src.BOAT_YEAR_MODEL, src.MOTOR_YEAR_MODEL, src.MOTOR_MANUFACTURER_MODEL, src.STATE_REG_DATE, src.STATE_REG_EXP_DATE, src.ENGINE_PURCHASED_COST, src.BACKEND_DISPLAY, src.POSITION_ORDER, src.STATUS_BOAT, src.SERVICE_START, src.SERVICE_END, src.CLEAN_STATUS, src.INSURANCE_REG_NO, src.BUOY_INSURANCE_STATUS, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_STYLE_BOATS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_STYLE_BOATS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_STYLE_BOATS;
/
