-- ============================================================================
-- Merge STG_STELLAR_BOOKING_PAYMENTS to DW_STELLAR_BOOKING_PAYMENTS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_BOOKING_PAYMENTS(
    p_inserted_count OUT NUMBER,
    p_updated_count OUT NUMBER
)
IS
BEGIN
    -- Insert new records that don't exist in DW
    INSERT INTO DW_STELLAR_BOOKING_PAYMENTS (
        ID, BOOKING_ID, CUSTOMER_ID, ADMIN_ID, FRONTEND, PAYMENT_FOR, PAYMENT_TYPE, CARD_TYPE, PAYMENT_TOTAL, CASH_TOTAL, CREDIT_TOTAL, AGENT_AR_TOTAL, CREDIT_LAST4, CREDIT_EXPIRY, BILLING_FIRST_NAME, BILLING_LAST_NAME, BILLING_STREET1, BILLING_STREET2, BILLING_CITY, BILLING_STATE, BILLING_COUNTRY, BILLING_ZIP, TRANS_ID, ORIGINAL_PAYMENT_ID, STATUS_PAYMENT, NOTES, IS_AGENT_AR, OFFLINE_TYPE, DOCK_MASTER_TICKET, MY_TASK_IT_ID, REPORT_BOATS, REPORT_PROPANE, REPORT_ACCESSORIES, REPORT_PARKING, REPORT_INSURANCE, REPORT_FUEL, REPORT_DAMAGES, REPORT_CLEANING, REPORT_LATE, REPORT_OTHER, REPORT_DISCOUNT, INTERNAL_APPLICATION_FEE, CC_PROCESSOR_FEE, CC_BRAND, CC_COUNTRY, CC_FUNDING, CC_CONNECT_TYPE, CC_CONNECT_ID, CC_PAYOUT_ID, CC_PAYOUT_DATE, EXTERNAL_CHARGE_ID, IS_SYNCED, STRIPE_READER_ID, CREATED_AT, UPDATED_AT, DELETED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
    )
    SELECT 
        src.ID, src.BOOKING_ID, src.CUSTOMER_ID, src.ADMIN_ID, src.FRONTEND, src.PAYMENT_FOR, src.PAYMENT_TYPE, src.CARD_TYPE, src.PAYMENT_TOTAL, src.CASH_TOTAL, src.CREDIT_TOTAL, src.AGENT_AR_TOTAL, src.CREDIT_LAST4, src.CREDIT_EXPIRY, src.BILLING_FIRST_NAME, src.BILLING_LAST_NAME, src.BILLING_STREET1, src.BILLING_STREET2, src.BILLING_CITY, src.BILLING_STATE, src.BILLING_COUNTRY, src.BILLING_ZIP, src.TRANS_ID, src.ORIGINAL_PAYMENT_ID, src.STATUS_PAYMENT, src.NOTES, src.IS_AGENT_AR, src.OFFLINE_TYPE, src.DOCK_MASTER_TICKET, src.MY_TASK_IT_ID, src.REPORT_BOATS, src.REPORT_PROPANE, src.REPORT_ACCESSORIES, src.REPORT_PARKING, src.REPORT_INSURANCE, src.REPORT_FUEL, src.REPORT_DAMAGES, src.REPORT_CLEANING, src.REPORT_LATE, src.REPORT_OTHER, src.REPORT_DISCOUNT, src.INTERNAL_APPLICATION_FEE, src.CC_PROCESSOR_FEE, src.CC_BRAND, src.CC_COUNTRY, src.CC_FUNDING, src.CC_CONNECT_TYPE, src.CC_CONNECT_ID, src.CC_PAYOUT_ID, src.CC_PAYOUT_DATE, src.EXTERNAL_CHARGE_ID, src.IS_SYNCED, src.STRIPE_READER_ID, src.CREATED_AT, src.UPDATED_AT, src.DELETED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
    FROM STG_STELLAR_BOOKING_PAYMENTS src
    WHERE NOT EXISTS (
        SELECT 1 FROM DW_STELLAR_BOOKING_PAYMENTS tgt WHERE tgt.ID = src.ID
    );
    
    p_inserted_count := SQL%ROWCOUNT;
    
    -- Update existing records where data has changed
    UPDATE DW_STELLAR_BOOKING_PAYMENTS tgt
    SET (
        tgt.BOOKING_ID, tgt.CUSTOMER_ID, tgt.ADMIN_ID, tgt.FRONTEND, tgt.PAYMENT_FOR, tgt.PAYMENT_TYPE, tgt.CARD_TYPE, tgt.PAYMENT_TOTAL, tgt.CASH_TOTAL, tgt.CREDIT_TOTAL, tgt.AGENT_AR_TOTAL, tgt.CREDIT_LAST4, tgt.CREDIT_EXPIRY, tgt.BILLING_FIRST_NAME, tgt.BILLING_LAST_NAME, tgt.BILLING_STREET1, tgt.BILLING_STREET2, tgt.BILLING_CITY, tgt.BILLING_STATE, tgt.BILLING_COUNTRY, tgt.BILLING_ZIP, tgt.TRANS_ID, tgt.ORIGINAL_PAYMENT_ID, tgt.STATUS_PAYMENT, tgt.NOTES, tgt.IS_AGENT_AR, tgt.OFFLINE_TYPE, tgt.DOCK_MASTER_TICKET, tgt.MY_TASK_IT_ID, tgt.REPORT_BOATS, tgt.REPORT_PROPANE, tgt.REPORT_ACCESSORIES, tgt.REPORT_PARKING, tgt.REPORT_INSURANCE, tgt.REPORT_FUEL, tgt.REPORT_DAMAGES, tgt.REPORT_CLEANING, tgt.REPORT_LATE, tgt.REPORT_OTHER, tgt.REPORT_DISCOUNT, tgt.INTERNAL_APPLICATION_FEE, tgt.CC_PROCESSOR_FEE, tgt.CC_BRAND, tgt.CC_COUNTRY, tgt.CC_FUNDING, tgt.CC_CONNECT_TYPE, tgt.CC_CONNECT_ID, tgt.CC_PAYOUT_ID, tgt.CC_PAYOUT_DATE, tgt.EXTERNAL_CHARGE_ID, tgt.IS_SYNCED, tgt.STRIPE_READER_ID, tgt.CREATED_AT, tgt.UPDATED_AT, tgt.DELETED_AT,
        tgt.DW_LAST_UPDATED
    ) = (
        SELECT 
            src.BOOKING_ID, src.CUSTOMER_ID, src.ADMIN_ID, src.FRONTEND, src.PAYMENT_FOR, src.PAYMENT_TYPE, src.CARD_TYPE, src.PAYMENT_TOTAL, src.CASH_TOTAL, src.CREDIT_TOTAL, src.AGENT_AR_TOTAL, src.CREDIT_LAST4, src.CREDIT_EXPIRY, src.BILLING_FIRST_NAME, src.BILLING_LAST_NAME, src.BILLING_STREET1, src.BILLING_STREET2, src.BILLING_CITY, src.BILLING_STATE, src.BILLING_COUNTRY, src.BILLING_ZIP, src.TRANS_ID, src.ORIGINAL_PAYMENT_ID, src.STATUS_PAYMENT, src.NOTES, src.IS_AGENT_AR, src.OFFLINE_TYPE, src.DOCK_MASTER_TICKET, src.MY_TASK_IT_ID, src.REPORT_BOATS, src.REPORT_PROPANE, src.REPORT_ACCESSORIES, src.REPORT_PARKING, src.REPORT_INSURANCE, src.REPORT_FUEL, src.REPORT_DAMAGES, src.REPORT_CLEANING, src.REPORT_LATE, src.REPORT_OTHER, src.REPORT_DISCOUNT, src.INTERNAL_APPLICATION_FEE, src.CC_PROCESSOR_FEE, src.CC_BRAND, src.CC_COUNTRY, src.CC_FUNDING, src.CC_CONNECT_TYPE, src.CC_CONNECT_ID, src.CC_PAYOUT_ID, src.CC_PAYOUT_DATE, src.EXTERNAL_CHARGE_ID, src.IS_SYNCED, src.STRIPE_READER_ID, src.CREATED_AT, src.UPDATED_AT, src.DELETED_AT,
            SYSTIMESTAMP
        FROM STG_STELLAR_BOOKING_PAYMENTS src
        WHERE tgt.ID = src.ID
    )
    WHERE EXISTS (
        SELECT 1 FROM STG_STELLAR_BOOKING_PAYMENTS src
        WHERE tgt.ID = src.ID
        AND (
            -- Only update if data has actually changed
            NVL(tgt.BOOKING_ID, -1) != NVL(src.BOOKING_ID, -1)
            OR NVL(tgt.CUSTOMER_ID, -1) != NVL(src.CUSTOMER_ID, -1)
            OR NVL(tgt.ADMIN_ID, -1) != NVL(src.ADMIN_ID, -1)
            OR NVL(tgt.FRONTEND, '~') != NVL(src.FRONTEND, '~')
            OR NVL(tgt.PAYMENT_FOR, '~') != NVL(src.PAYMENT_FOR, '~')
            OR NVL(tgt.PAYMENT_TYPE, '~') != NVL(src.PAYMENT_TYPE, '~')
            OR NVL(tgt.CARD_TYPE, '~') != NVL(src.CARD_TYPE, '~')
            OR NVL(tgt.PAYMENT_TOTAL, '~') != NVL(src.PAYMENT_TOTAL, '~')
            OR NVL(tgt.CASH_TOTAL, '~') != NVL(src.CASH_TOTAL, '~')
            OR NVL(tgt.CREDIT_TOTAL, '~') != NVL(src.CREDIT_TOTAL, '~')
            OR NVL(tgt.AGENT_AR_TOTAL, '~') != NVL(src.AGENT_AR_TOTAL, '~')
            OR NVL(tgt.CREDIT_LAST4, '~') != NVL(src.CREDIT_LAST4, '~')
            OR NVL(tgt.CREDIT_EXPIRY, '~') != NVL(src.CREDIT_EXPIRY, '~')
            OR NVL(tgt.BILLING_FIRST_NAME, '~') != NVL(src.BILLING_FIRST_NAME, '~')
            OR NVL(tgt.BILLING_LAST_NAME, '~') != NVL(src.BILLING_LAST_NAME, '~')
            OR NVL(tgt.BILLING_STREET1, '~') != NVL(src.BILLING_STREET1, '~')
            OR NVL(tgt.BILLING_STREET2, '~') != NVL(src.BILLING_STREET2, '~')
            OR NVL(tgt.BILLING_CITY, '~') != NVL(src.BILLING_CITY, '~')
            OR NVL(tgt.BILLING_STATE, '~') != NVL(src.BILLING_STATE, '~')
            OR NVL(tgt.BILLING_COUNTRY, -1) != NVL(src.BILLING_COUNTRY, -1)
            OR NVL(tgt.BILLING_ZIP, '~') != NVL(src.BILLING_ZIP, '~')
            OR NVL(tgt.TRANS_ID, -1) != NVL(src.TRANS_ID, -1)
            OR NVL(tgt.ORIGINAL_PAYMENT_ID, -1) != NVL(src.ORIGINAL_PAYMENT_ID, -1)
            OR NVL(tgt.STATUS_PAYMENT, '~') != NVL(src.STATUS_PAYMENT, '~')
            -- OR NVL(tgt.NOTES, '~') != NVL(src.NOTES, '~')  -- NCLOB: cannot compare
            OR NVL(tgt.IS_AGENT_AR, '~') != NVL(src.IS_AGENT_AR, '~')
            OR NVL(tgt.OFFLINE_TYPE, '~') != NVL(src.OFFLINE_TYPE, '~')
            -- OR NVL(tgt.DOCK_MASTER_TICKET, '~') != NVL(src.DOCK_MASTER_TICKET, '~')  -- NCLOB: cannot compare
            OR NVL(tgt.MY_TASK_IT_ID, -1) != NVL(src.MY_TASK_IT_ID, -1)
            OR NVL(tgt.REPORT_BOATS, '~') != NVL(src.REPORT_BOATS, '~')
            OR NVL(tgt.REPORT_PROPANE, '~') != NVL(src.REPORT_PROPANE, '~')
            OR NVL(tgt.REPORT_ACCESSORIES, '~') != NVL(src.REPORT_ACCESSORIES, '~')
            OR NVL(tgt.REPORT_PARKING, '~') != NVL(src.REPORT_PARKING, '~')
            OR NVL(tgt.REPORT_INSURANCE, '~') != NVL(src.REPORT_INSURANCE, '~')
            OR NVL(tgt.REPORT_FUEL, '~') != NVL(src.REPORT_FUEL, '~')
            OR NVL(tgt.REPORT_DAMAGES, '~') != NVL(src.REPORT_DAMAGES, '~')
            OR NVL(tgt.REPORT_CLEANING, '~') != NVL(src.REPORT_CLEANING, '~')
            OR NVL(tgt.REPORT_LATE, '~') != NVL(src.REPORT_LATE, '~')
            OR NVL(tgt.REPORT_OTHER, '~') != NVL(src.REPORT_OTHER, '~')
            OR NVL(tgt.REPORT_DISCOUNT, -1) != NVL(src.REPORT_DISCOUNT, -1)
            OR NVL(tgt.INTERNAL_APPLICATION_FEE, -1) != NVL(src.INTERNAL_APPLICATION_FEE, -1)
            OR NVL(tgt.CC_PROCESSOR_FEE, -1) != NVL(src.CC_PROCESSOR_FEE, -1)
            OR NVL(tgt.CC_BRAND, '~') != NVL(src.CC_BRAND, '~')
            OR NVL(tgt.CC_COUNTRY, -1) != NVL(src.CC_COUNTRY, -1)
            OR NVL(tgt.CC_FUNDING, '~') != NVL(src.CC_FUNDING, '~')
            OR NVL(tgt.CC_CONNECT_TYPE, '~') != NVL(src.CC_CONNECT_TYPE, '~')
            OR NVL(tgt.CC_CONNECT_ID, -1) != NVL(src.CC_CONNECT_ID, -1)
            OR NVL(tgt.CC_PAYOUT_ID, -1) != NVL(src.CC_PAYOUT_ID, -1)
            OR NVL(tgt.CC_PAYOUT_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CC_PAYOUT_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.EXTERNAL_CHARGE_ID, -1) != NVL(src.EXTERNAL_CHARGE_ID, -1)
            OR NVL(tgt.IS_SYNCED, '~') != NVL(src.IS_SYNCED, '~')
            OR NVL(tgt.STRIPE_READER_ID, -1) != NVL(src.STRIPE_READER_ID, -1)
            OR NVL(tgt.CREATED_AT, '~') != NVL(src.CREATED_AT, '~')
            OR NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.DELETED_AT, '~') != NVL(src.DELETED_AT, '~')
        )
    );
    
    p_updated_count := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_BOOKING_PAYMENTS: Inserted ' || p_inserted_count || ', Updated ' || p_updated_count || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_BOOKING_PAYMENTS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_BOOKING_PAYMENTS;
