-- ============================================================================
-- Merge STG_MOLO_TRANSACTIONS to DW_MOLO_TRANSACTIONS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_TRANSACTIONS(
    p_inserted_count OUT NUMBER,
    p_updated_count OUT NUMBER
)
IS
BEGIN
    -- Insert new records that don't exist in DW
    INSERT INTO DW_MOLO_TRANSACTIONS (
        ID, MARINA_LOCATION_ID, CREATION_TIME, INVOICE_ID, TRANSACTION_TYPE_ID, TRANSACTION_METHOD_ID, VALUE_FIELD, IS_REFUNDED, CUSTOMER_IP_ADDRESS, CUSTOMER_DEVICE, REFUND_REASON, AUX, CHECK_NUMBER, CC_TYPE, INVOICE_ITEM_ID, SENT_TO_XERO, OVERPAYMENT_ID, PAYMENT_COLLECTED_OFFLINE, PART_OF_OVERPAYMENT, PREPAYMENT_ID, ACCOUNT_TRANSACTION_TRANSACTION_ID, PAYMENT_ID, CREATION_DATE, ASPNET_USER_ID, HASH_ID, CUSTOM_TRANSACTION_METHODS_ID, REFERENCE, IS_VOID, AMOUNT_REFUNDED, STRIPE_TRANSACTION_DATA_ID, PAYMENT_INTENT_ID, SENT_TO_PAYOUT, STRIPE_AUTHORIZATIONS_ID, STRIPE_RESPONSE_ID, STRIPE_READER_SERIAL_NUMBER, STRIPE_TERMINAL_ID, CREATED_ON_MOBILE, ONLINE_PERCENT_FEE, ONLINE_FEE_AMOUNT, SCHEDULED_FOR_ONLINE_FEE_CRON, ONLINE_PAYMENT_FEE_ID, BANK_NAME, LAST4, STRIPE_BANK_ACCOUNT_ID, STRIPE_BATCH_ID, ROUTING_NUMBER, FULLY_REFUNDED, LAST_UPDATED, PAYMENT_SOURCE,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
    )
    SELECT 
        src.ID, src.MARINA_LOCATION_ID, src.CREATION_TIME, src.INVOICE_ID, src.TRANSACTION_TYPE_ID, src.TRANSACTION_METHOD_ID, src.VALUE_FIELD, src.IS_REFUNDED, src.CUSTOMER_IP_ADDRESS, src.CUSTOMER_DEVICE, src.REFUND_REASON, src.AUX, src.CHECK_NUMBER, src.CC_TYPE, src.INVOICE_ITEM_ID, src.SENT_TO_XERO, src.OVERPAYMENT_ID, src.PAYMENT_COLLECTED_OFFLINE, src.PART_OF_OVERPAYMENT, src.PREPAYMENT_ID, src.ACCOUNT_TRANSACTION_TRANSACTION_ID, src.PAYMENT_ID, src.CREATION_DATE, src.ASPNET_USER_ID, src.HASH_ID, src.CUSTOM_TRANSACTION_METHODS_ID, src.REFERENCE, src.IS_VOID, src.AMOUNT_REFUNDED, src.STRIPE_TRANSACTION_DATA_ID, src.PAYMENT_INTENT_ID, src.SENT_TO_PAYOUT, src.STRIPE_AUTHORIZATIONS_ID, src.STRIPE_RESPONSE_ID, src.STRIPE_READER_SERIAL_NUMBER, src.STRIPE_TERMINAL_ID, src.CREATED_ON_MOBILE, src.ONLINE_PERCENT_FEE, src.ONLINE_FEE_AMOUNT, src.SCHEDULED_FOR_ONLINE_FEE_CRON, src.ONLINE_PAYMENT_FEE_ID, src.BANK_NAME, src.LAST4, src.STRIPE_BANK_ACCOUNT_ID, src.STRIPE_BATCH_ID, src.ROUTING_NUMBER, src.FULLY_REFUNDED, src.LAST_UPDATED, src.PAYMENT_SOURCE,
            SYSTIMESTAMP,
            SYSTIMESTAMP
    FROM STG_MOLO_TRANSACTIONS src
    WHERE NOT EXISTS (
        SELECT 1 FROM DW_MOLO_TRANSACTIONS tgt WHERE tgt.ID = src.ID
    );
    
    p_inserted_count := SQL%ROWCOUNT;
    
    -- Update existing records where data has changed
    UPDATE DW_MOLO_TRANSACTIONS tgt
    SET (
        tgt.MARINA_LOCATION_ID, tgt.CREATION_TIME, tgt.INVOICE_ID, tgt.TRANSACTION_TYPE_ID, tgt.TRANSACTION_METHOD_ID, tgt.VALUE_FIELD, tgt.IS_REFUNDED, tgt.CUSTOMER_IP_ADDRESS, tgt.CUSTOMER_DEVICE, tgt.REFUND_REASON, tgt.AUX, tgt.CHECK_NUMBER, tgt.CC_TYPE, tgt.INVOICE_ITEM_ID, tgt.SENT_TO_XERO, tgt.OVERPAYMENT_ID, tgt.PAYMENT_COLLECTED_OFFLINE, tgt.PART_OF_OVERPAYMENT, tgt.PREPAYMENT_ID, tgt.ACCOUNT_TRANSACTION_TRANSACTION_ID, tgt.PAYMENT_ID, tgt.CREATION_DATE, tgt.ASPNET_USER_ID, tgt.HASH_ID, tgt.CUSTOM_TRANSACTION_METHODS_ID, tgt.REFERENCE, tgt.IS_VOID, tgt.AMOUNT_REFUNDED, tgt.STRIPE_TRANSACTION_DATA_ID, tgt.PAYMENT_INTENT_ID, tgt.SENT_TO_PAYOUT, tgt.STRIPE_AUTHORIZATIONS_ID, tgt.STRIPE_RESPONSE_ID, tgt.STRIPE_READER_SERIAL_NUMBER, tgt.STRIPE_TERMINAL_ID, tgt.CREATED_ON_MOBILE, tgt.ONLINE_PERCENT_FEE, tgt.ONLINE_FEE_AMOUNT, tgt.SCHEDULED_FOR_ONLINE_FEE_CRON, tgt.ONLINE_PAYMENT_FEE_ID, tgt.BANK_NAME, tgt.LAST4, tgt.STRIPE_BANK_ACCOUNT_ID, tgt.STRIPE_BATCH_ID, tgt.ROUTING_NUMBER, tgt.FULLY_REFUNDED, tgt.LAST_UPDATED, tgt.PAYMENT_SOURCE,
        tgt.DW_LAST_UPDATED
    ) = (
        SELECT 
            src.MARINA_LOCATION_ID, src.CREATION_TIME, src.INVOICE_ID, src.TRANSACTION_TYPE_ID, src.TRANSACTION_METHOD_ID, src.VALUE_FIELD, src.IS_REFUNDED, src.CUSTOMER_IP_ADDRESS, src.CUSTOMER_DEVICE, src.REFUND_REASON, src.AUX, src.CHECK_NUMBER, src.CC_TYPE, src.INVOICE_ITEM_ID, src.SENT_TO_XERO, src.OVERPAYMENT_ID, src.PAYMENT_COLLECTED_OFFLINE, src.PART_OF_OVERPAYMENT, src.PREPAYMENT_ID, src.ACCOUNT_TRANSACTION_TRANSACTION_ID, src.PAYMENT_ID, src.CREATION_DATE, src.ASPNET_USER_ID, src.HASH_ID, src.CUSTOM_TRANSACTION_METHODS_ID, src.REFERENCE, src.IS_VOID, src.AMOUNT_REFUNDED, src.STRIPE_TRANSACTION_DATA_ID, src.PAYMENT_INTENT_ID, src.SENT_TO_PAYOUT, src.STRIPE_AUTHORIZATIONS_ID, src.STRIPE_RESPONSE_ID, src.STRIPE_READER_SERIAL_NUMBER, src.STRIPE_TERMINAL_ID, src.CREATED_ON_MOBILE, src.ONLINE_PERCENT_FEE, src.ONLINE_FEE_AMOUNT, src.SCHEDULED_FOR_ONLINE_FEE_CRON, src.ONLINE_PAYMENT_FEE_ID, src.BANK_NAME, src.LAST4, src.STRIPE_BANK_ACCOUNT_ID, src.STRIPE_BATCH_ID, src.ROUTING_NUMBER, src.FULLY_REFUNDED, src.LAST_UPDATED, src.PAYMENT_SOURCE,
            SYSTIMESTAMP
        FROM STG_MOLO_TRANSACTIONS src
        WHERE tgt.ID = src.ID
    )
    WHERE EXISTS (
        SELECT 1 FROM STG_MOLO_TRANSACTIONS src
        WHERE tgt.ID = src.ID
        AND (
            -- Only update if data has actually changed
            NVL(tgt.MARINA_LOCATION_ID, -1) != NVL(src.MARINA_LOCATION_ID, -1)
            OR NVL(tgt.CREATION_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CREATION_TIME, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.INVOICE_ID, -1) != NVL(src.INVOICE_ID, -1)
            OR NVL(tgt.TRANSACTION_TYPE_ID, -1) != NVL(src.TRANSACTION_TYPE_ID, -1)
            OR NVL(tgt.TRANSACTION_METHOD_ID, -1) != NVL(src.TRANSACTION_METHOD_ID, -1)
            OR NVL(tgt.VALUE_FIELD, '~') != NVL(src.VALUE_FIELD, '~')
            OR NVL(tgt.IS_REFUNDED, '~') != NVL(src.IS_REFUNDED, '~')
            OR NVL(tgt.CUSTOMER_IP_ADDRESS, '~') != NVL(src.CUSTOMER_IP_ADDRESS, '~')
            OR NVL(tgt.CUSTOMER_DEVICE, '~') != NVL(src.CUSTOMER_DEVICE, '~')
            OR NVL(tgt.REFUND_REASON, '~') != NVL(src.REFUND_REASON, '~')
            OR NVL(tgt.AUX, '~') != NVL(src.AUX, '~')
            OR NVL(tgt.CHECK_NUMBER, '~') != NVL(src.CHECK_NUMBER, '~')
            OR NVL(tgt.CC_TYPE, '~') != NVL(src.CC_TYPE, '~')
            OR NVL(tgt.INVOICE_ITEM_ID, -1) != NVL(src.INVOICE_ITEM_ID, -1)
            OR NVL(tgt.SENT_TO_XERO, '~') != NVL(src.SENT_TO_XERO, '~')
            OR NVL(tgt.OVERPAYMENT_ID, '~') != NVL(src.OVERPAYMENT_ID, '~')
            OR NVL(tgt.PAYMENT_COLLECTED_OFFLINE, '~') != NVL(src.PAYMENT_COLLECTED_OFFLINE, '~')
            OR NVL(tgt.PART_OF_OVERPAYMENT, '~') != NVL(src.PART_OF_OVERPAYMENT, '~')
            OR NVL(tgt.PREPAYMENT_ID, '~') != NVL(src.PREPAYMENT_ID, '~')
            OR NVL(tgt.ACCOUNT_TRANSACTION_TRANSACTION_ID, -1) != NVL(src.ACCOUNT_TRANSACTION_TRANSACTION_ID, -1)
            OR NVL(tgt.PAYMENT_ID, -1) != NVL(src.PAYMENT_ID, -1)
            OR NVL(tgt.CREATION_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.CREATION_DATE, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.ASPNET_USER_ID, '~') != NVL(src.ASPNET_USER_ID, '~')
            OR NVL(tgt.HASH_ID, '~') != NVL(src.HASH_ID, '~')
            OR NVL(tgt.CUSTOM_TRANSACTION_METHODS_ID, -1) != NVL(src.CUSTOM_TRANSACTION_METHODS_ID, -1)
            OR NVL(tgt.REFERENCE, '~') != NVL(src.REFERENCE, '~')
            OR NVL(tgt.IS_VOID, '~') != NVL(src.IS_VOID, '~')
            OR NVL(tgt.AMOUNT_REFUNDED, -9999999) != NVL(src.AMOUNT_REFUNDED, -9999999)
            OR NVL(tgt.STRIPE_TRANSACTION_DATA_ID, -1) != NVL(src.STRIPE_TRANSACTION_DATA_ID, -1)
            OR NVL(tgt.PAYMENT_INTENT_ID, '~') != NVL(src.PAYMENT_INTENT_ID, '~')
            OR NVL(tgt.SENT_TO_PAYOUT, '~') != NVL(src.SENT_TO_PAYOUT, '~')
            OR NVL(tgt.STRIPE_AUTHORIZATIONS_ID, -1) != NVL(src.STRIPE_AUTHORIZATIONS_ID, -1)
            OR NVL(tgt.STRIPE_RESPONSE_ID, -1) != NVL(src.STRIPE_RESPONSE_ID, -1)
            OR NVL(tgt.STRIPE_READER_SERIAL_NUMBER, '~') != NVL(src.STRIPE_READER_SERIAL_NUMBER, '~')
            OR NVL(tgt.STRIPE_TERMINAL_ID, '~') != NVL(src.STRIPE_TERMINAL_ID, '~')
            OR NVL(tgt.CREATED_ON_MOBILE, '~') != NVL(src.CREATED_ON_MOBILE, '~')
            OR NVL(tgt.ONLINE_PERCENT_FEE, -9999999) != NVL(src.ONLINE_PERCENT_FEE, -9999999)
            OR NVL(tgt.ONLINE_FEE_AMOUNT, -9999999) != NVL(src.ONLINE_FEE_AMOUNT, -9999999)
            OR NVL(tgt.SCHEDULED_FOR_ONLINE_FEE_CRON, -1) != NVL(src.SCHEDULED_FOR_ONLINE_FEE_CRON, -1)
            OR NVL(tgt.ONLINE_PAYMENT_FEE_ID, -1) != NVL(src.ONLINE_PAYMENT_FEE_ID, -1)
            OR NVL(tgt.BANK_NAME, '~') != NVL(src.BANK_NAME, '~')
            OR NVL(tgt.LAST4, '~') != NVL(src.LAST4, '~')
            OR NVL(tgt.STRIPE_BANK_ACCOUNT_ID, -1) != NVL(src.STRIPE_BANK_ACCOUNT_ID, -1)
            OR NVL(tgt.STRIPE_BATCH_ID, -1) != NVL(src.STRIPE_BATCH_ID, -1)
            OR NVL(tgt.ROUTING_NUMBER, '~') != NVL(src.ROUTING_NUMBER, '~')
            OR NVL(tgt.FULLY_REFUNDED, '~') != NVL(src.FULLY_REFUNDED, '~')
            OR NVL(tgt.LAST_UPDATED, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD')) != NVL(src.LAST_UPDATED, TO_TIMESTAMP('1900-01-01', 'YYYY-MM-DD'))
            OR NVL(tgt.PAYMENT_SOURCE, '~') != NVL(src.PAYMENT_SOURCE, '~')
        )
    );
    
    p_updated_count := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_TRANSACTIONS: Inserted ' || p_inserted_count || ', Updated ' || p_updated_count || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_TRANSACTIONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_TRANSACTIONS;
