
  CREATE OR REPLACE EDITIONABLE PROCEDURE "API_USER"."SP_MERGE_STELLAR_ACCESSORY_OPTIONS" 
IS
    v_merged NUMBER := 0;
BEGIN
    MERGE INTO DW_STELLAR_ACCESSORY_OPTIONS tgt
    USING STG_STELLAR_ACCESSORY_OPTIONS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.ACCESSORY_ID = src.ACCESSORY_ID,
            tgt.VALUE_TEXT = src.VALUE_TEXT,
            tgt.USE_STRIPED_BACKGROUND = src.USE_STRIPED_BACKGROUND,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ID, ACCESSORY_ID, VALUE_TEXT, USE_STRIPED_BACKGROUND, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.ACCESSORY_ID, src.VALUE_TEXT, src.USE_STRIPED_BACKGROUND, src.CREATED_AT, src.UPDATED_AT,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
    
    v_merged := SQL%ROWCOUNT;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_ACCESSORY_OPTIONS: Merged ' || v_merged || ' records');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_ACCESSORY_OPTIONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_ACCESSORY_OPTIONS;
/