
  CREATE OR REPLACE EDITIONABLE PROCEDURE "API_USER"."SP_MERGE_STELLAR_CUSTOMERS" 
IS
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_timestamp TIMESTAMP := SYSTIMESTAMP;
BEGIN
    MERGE INTO DW_STELLAR_CUSTOMERS tgt
    USING STG_STELLAR_CUSTOMERS src
    ON (tgt.USER_ID = src.USER_ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.CLUB_PRINCIPAL_USER_ID = src.CLUB_PRINCIPAL_USER_ID,
            tgt.COUPON_ID = src.COUPON_ID,
            tgt.CLUB_TIER_ID = src.CLUB_TIER_ID,
            tgt.FIRST_NAME = src.FIRST_NAME,
            tgt.LAST_NAME = src.LAST_NAME,
            tgt.MIDDLE_NAME = src.MIDDLE_NAME,
            tgt.GENDER = src.GENDER,
            tgt.PHONE = src.PHONE,
            tgt.CELL = src.CELL,
            tgt.EMERGENCY_NAME = src.EMERGENCY_NAME,
            tgt.EMERGENCY_PHONE = src.EMERGENCY_PHONE,
            tgt.SECONDARY_EMAIL = src.SECONDARY_EMAIL,
            tgt.BILLING_STREET1 = src.BILLING_STREET1,
            tgt.BILLING_STREET2 = src.BILLING_STREET2,
            tgt.BILLING_CITY = src.BILLING_CITY,
            tgt.BILLING_STATE = src.BILLING_STATE,
            tgt.BILLING_COUNTRY = src.BILLING_COUNTRY,
            tgt.BILLING_ZIP = src.BILLING_ZIP,
            tgt.MAILING_STREET1 = src.MAILING_STREET1,
            tgt.MAILING_STREET2 = src.MAILING_STREET2,
            tgt.MAILING_CITY = src.MAILING_CITY,
            tgt.MAILING_STATE = src.MAILING_STATE,
            tgt.MAILING_COUNTRY = src.MAILING_COUNTRY,
            tgt.MAILING_ZIP = src.MAILING_ZIP,
            tgt.NUM_KIDS = src.NUM_KIDS,
            tgt.REFERRER = src.REFERRER,
            tgt.SERVICES = src.SERVICES,
            tgt.DATE_OF_BIRTH = src.DATE_OF_BIRTH,
            tgt.DL_STATE = src.DL_STATE,
            tgt.DL_COUNTRY = src.DL_COUNTRY,
            tgt.DL_NUMBER = src.DL_NUMBER,
            tgt.NOTES = src.NOTES,
            tgt.INTERNAL_NOTES = src.INTERNAL_NOTES,
            tgt.CLUB_STATUS = src.CLUB_STATUS,
            tgt.CLUB_START_DATE = src.CLUB_START_DATE,
            tgt.CLUB_USE_RECURRING_BILLING = src.CLUB_USE_RECURRING_BILLING,
            tgt.CLUB_RECURRING_BILLING_START_DATE = src.CLUB_RECURRING_BILLING_START_DATE,
            tgt.BALANCE = src.BALANCE,
            tgt.BOAT_DAMAGE_RESPONSIBILITY_COVERAGE = src.BOAT_DAMAGE_RESPONSIBILITY_COVERAGE,
            tgt.PENALTY_POINTS = src.PENALTY_POINTS,
            tgt.OPEN_BALANCE_THRESHOLD = src.OPEN_BALANCE_THRESHOLD,
            tgt.CLUB_END_DATE = src.CLUB_END_DATE,
            tgt.CC_SAVED_NAME = src.CC_SAVED_NAME,
            tgt.CC_SAVED_LAST4 = src.CC_SAVED_LAST4,
            tgt.CC_SAVED_EXPIRY = src.CC_SAVED_EXPIRY,
            tgt.CC_SAVED_PROFILE_ID = src.CC_SAVED_PROFILE_ID,
            tgt.CC_SAVED_METHOD_ID = src.CC_SAVED_METHOD_ID,
            tgt.CC_SAVED_ADDRESS_ID = src.CC_SAVED_ADDRESS_ID,
            tgt.EXTERNAL_ID = src.EXTERNAL_ID,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = v_timestamp
        WHERE (
            NVL(tgt.USER_ID, -999) <> NVL(src.USER_ID, -999) OR
            NVL(tgt.CLUB_PRINCIPAL_USER_ID, -999) <> NVL(src.CLUB_PRINCIPAL_USER_ID, -999) OR
            NVL(tgt.COUPON_ID, -999) <> NVL(src.COUPON_ID, -999) OR
            NVL(tgt.CLUB_TIER_ID, -999) <> NVL(src.CLUB_TIER_ID, -999) OR
            NVL(tgt.FIRST_NAME, '~NULL~') <> NVL(src.FIRST_NAME, '~NULL~') OR
            NVL(tgt.LAST_NAME, '~NULL~') <> NVL(src.LAST_NAME, '~NULL~') OR
            NVL(tgt.MIDDLE_NAME, '~NULL~') <> NVL(src.MIDDLE_NAME, '~NULL~') OR
            NVL(tgt.GENDER, '~NULL~') <> NVL(src.GENDER, '~NULL~') OR
            NVL(tgt.PHONE, '~NULL~') <> NVL(src.PHONE, '~NULL~') OR
            NVL(tgt.CELL, '~NULL~') <> NVL(src.CELL, '~NULL~') OR
            NVL(tgt.EMERGENCY_NAME, '~NULL~') <> NVL(src.EMERGENCY_NAME, '~NULL~') OR
            NVL(tgt.EMERGENCY_PHONE, '~NULL~') <> NVL(src.EMERGENCY_PHONE, '~NULL~') OR
            NVL(tgt.BILLING_STREET1, '~NULL~') <> NVL(src.BILLING_STREET1, '~NULL~') OR
            NVL(tgt.BILLING_STREET2, '~NULL~') <> NVL(src.BILLING_STREET2, '~NULL~') OR
            NVL(tgt.BILLING_CITY, '~NULL~') <> NVL(src.BILLING_CITY, '~NULL~') OR
            NVL(tgt.BILLING_STATE, '~NULL~') <> NVL(src.BILLING_STATE, '~NULL~') OR
            NVL(tgt.BILLING_COUNTRY, '~NULL~') <> NVL(src.BILLING_COUNTRY, '~NULL~') OR
            NVL(tgt.BILLING_ZIP, '~NULL~') <> NVL(src.BILLING_ZIP, '~NULL~') OR
            NVL(tgt.MAILING_STREET1, '~NULL~') <> NVL(src.MAILING_STREET1, '~NULL~') OR
            NVL(tgt.MAILING_STREET2, '~NULL~') <> NVL(src.MAILING_STREET2, '~NULL~') OR
            NVL(tgt.MAILING_CITY, '~NULL~') <> NVL(src.MAILING_CITY, '~NULL~') OR
            NVL(tgt.MAILING_STATE, '~NULL~') <> NVL(src.MAILING_STATE, '~NULL~') OR
            NVL(tgt.MAILING_COUNTRY, '~NULL~') <> NVL(src.MAILING_COUNTRY, '~NULL~') OR
            NVL(tgt.MAILING_ZIP, '~NULL~') <> NVL(src.MAILING_ZIP, '~NULL~') OR
            NVL(tgt.NUM_KIDS, '~NULL~') <> NVL(src.NUM_KIDS, '~NULL~') OR
            NVL(tgt.REFERRER, '~NULL~') <> NVL(src.REFERRER, '~NULL~') OR
            NVL(tgt.SERVICES, '~NULL~') <> NVL(src.SERVICES, '~NULL~') OR
            NVL(tgt.DATE_OF_BIRTH, '~NULL~') <> NVL(src.DATE_OF_BIRTH, '~NULL~') OR
            NVL(tgt.DL_STATE, '~NULL~') <> NVL(src.DL_STATE, '~NULL~') OR
            NVL(tgt.DL_COUNTRY, '~NULL~') <> NVL(src.DL_COUNTRY, '~NULL~') OR
            NVL(tgt.DL_NUMBER, '~NULL~') <> NVL(src.DL_NUMBER, '~NULL~') OR
            NVL(tgt.CLUB_STATUS, '~NULL~') <> NVL(src.CLUB_STATUS, '~NULL~') OR
            NVL(tgt.CLUB_START_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.CLUB_START_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.CLUB_USE_RECURRING_BILLING, '~NULL~') <> NVL(src.CLUB_USE_RECURRING_BILLING, '~NULL~') OR
            NVL(tgt.CLUB_RECURRING_BILLING_START_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.CLUB_RECURRING_BILLING_START_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.BALANCE, -999.999) <> NVL(src.BALANCE, -999.999) OR
            NVL(tgt.BOAT_DAMAGE_RESPONSIBILITY_COVERAGE, '~NULL~') <> NVL(src.BOAT_DAMAGE_RESPONSIBILITY_COVERAGE, '~NULL~') OR
            NVL(tgt.PENALTY_POINTS, -999) <> NVL(src.PENALTY_POINTS, -999) OR
            NVL(tgt.OPEN_BALANCE_THRESHOLD, -999) <> NVL(src.OPEN_BALANCE_THRESHOLD, -999) OR
            NVL(tgt.CLUB_END_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.CLUB_END_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.CC_SAVED_NAME, '~NULL~') <> NVL(src.CC_SAVED_NAME, '~NULL~') OR
            NVL(tgt.CC_SAVED_LAST4, -999) <> NVL(src.CC_SAVED_LAST4, -999) OR
            NVL(tgt.CC_SAVED_EXPIRY, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.CC_SAVED_EXPIRY, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.CC_SAVED_PROFILE_ID, '~NULL~') <> NVL(src.CC_SAVED_PROFILE_ID, '~NULL~') OR
            NVL(tgt.CC_SAVED_METHOD_ID, '~NULL~') <> NVL(src.CC_SAVED_METHOD_ID, '~NULL~') OR
            NVL(tgt.CC_SAVED_ADDRESS_ID, '~NULL~') <> NVL(src.CC_SAVED_ADDRESS_ID, '~NULL~') OR
            NVL(tgt.EXTERNAL_ID, '~NULL~') <> NVL(src.EXTERNAL_ID, '~NULL~') OR
            NVL(tgt.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'))
        )
    WHEN NOT MATCHED THEN
        INSERT (
            USER_ID, CLUB_PRINCIPAL_USER_ID, COUPON_ID, CLUB_TIER_ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER, PHONE, CELL, EMERGENCY_NAME, EMERGENCY_PHONE, SECONDARY_EMAIL, BILLING_STREET1, BILLING_STREET2, BILLING_CITY, BILLING_STATE, BILLING_COUNTRY, BILLING_ZIP, MAILING_STREET1, MAILING_STREET2, MAILING_CITY, MAILING_STATE, MAILING_COUNTRY, MAILING_ZIP, NUM_KIDS, REFERRER, SERVICES, DATE_OF_BIRTH, DL_STATE, DL_COUNTRY, DL_NUMBER, NOTES, INTERNAL_NOTES, CLUB_STATUS, CLUB_START_DATE, CLUB_USE_RECURRING_BILLING, CLUB_RECURRING_BILLING_START_DATE, BALANCE, BOAT_DAMAGE_RESPONSIBILITY_COVERAGE, PENALTY_POINTS, OPEN_BALANCE_THRESHOLD, CLUB_END_DATE, CC_SAVED_NAME, CC_SAVED_LAST4, CC_SAVED_EXPIRY, CC_SAVED_PROFILE_ID, CC_SAVED_METHOD_ID, CC_SAVED_ADDRESS_ID, EXTERNAL_ID, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.USER_ID, src.CLUB_PRINCIPAL_USER_ID, src.COUPON_ID, src.CLUB_TIER_ID, src.FIRST_NAME, src.LAST_NAME, src.MIDDLE_NAME, src.GENDER, src.PHONE, src.CELL, src.EMERGENCY_NAME, src.EMERGENCY_PHONE, src.SECONDARY_EMAIL, src.BILLING_STREET1, src.BILLING_STREET2, src.BILLING_CITY, src.BILLING_STATE, src.BILLING_COUNTRY, src.BILLING_ZIP, src.MAILING_STREET1, src.MAILING_STREET2, src.MAILING_CITY, src.MAILING_STATE, src.MAILING_COUNTRY, src.MAILING_ZIP, src.NUM_KIDS, src.REFERRER, src.SERVICES, src.DATE_OF_BIRTH, src.DL_STATE, src.DL_COUNTRY, src.DL_NUMBER, src.NOTES, src.INTERNAL_NOTES, src.CLUB_STATUS, src.CLUB_START_DATE, src.CLUB_USE_RECURRING_BILLING, src.CLUB_RECURRING_BILLING_START_DATE, src.BALANCE, src.BOAT_DAMAGE_RESPONSIBILITY_COVERAGE, src.PENALTY_POINTS, src.OPEN_BALANCE_THRESHOLD, src.CLUB_END_DATE, src.CC_SAVED_NAME, src.CC_SAVED_LAST4, src.CC_SAVED_EXPIRY, src.CC_SAVED_PROFILE_ID, src.CC_SAVED_METHOD_ID, src.CC_SAVED_ADDRESS_ID, src.EXTERNAL_ID, src.CREATED_AT, src.UPDATED_AT,
            v_timestamp,
            v_timestamp
        );
    
    -- Count inserts and updates
    SELECT COUNT(*) INTO v_inserted 
    FROM DW_STELLAR_CUSTOMERS 
    WHERE DW_LAST_INSERTED = v_timestamp;
    
    SELECT COUNT(*) INTO v_updated 
    FROM DW_STELLAR_CUSTOMERS 
    WHERE DW_LAST_UPDATED = v_timestamp 
    AND DW_LAST_INSERTED < v_timestamp;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_CUSTOMERS: ' || v_inserted || ' inserted, ' || v_updated || ' updated');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_CUSTOMERS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_CUSTOMERS;
/